var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,p=!1,r,la=a=>a.startsWith("file://");
function na(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);v=new Uint8Array(a);qa=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);y=new Float32Array(a);z=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var pa,w,t,y,z,qa,x,v,xa=a=>{for(;0<a.length;)a.shift()(h)},ya=[],za=[],Aa=()=>{var a=h.preRun.shift();za.push(a)},A=0,B=null,Ba=!0,Ca=globalThis.TextDecoder&&new TextDecoder,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Da=0,Ea=[0,31,60,91,121,152,182,213,244,274,305,335],Fa=[0,31,59,90,120,151,181,212,243,273,304,334],D={},Ga=a=>{a instanceof wa||"unwind"==a||fa(1,a)},Ha=a=>{r=a;Ba||0<Da||(h.onExit?.(a),p=!0);fa(a,new wa(a))},Ia=()=>{if(!(Ba||0<Da))try{var a=r;r=a;Ha(a)}catch(b){Ga(b)}},Ja=a=>{if(!p)try{a()}catch(b){Ga(b)}finally{Ia()}},G=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=
a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Ra=(a,b)=>{Ka=a;La=b;if(H)if(Ma||=!0,0==a)I=function(){setTimeout(Na,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)I=function(){Pa(Na)};else{if(!Qa)if(globalThis.setImmediate)Qa=
setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Qa(Na)}}},$a=(a,b,c,d,e)=>{function g(){return f<Sa?(Ia(),!1):!0}H=a;Ta=d;var f=Sa;Ma=!1;Na=function(){if(!p)if(0<Ua.length){var l=Ua.shift();l.ae(l.Pd);if(Va){var n=
Va,q=0==n%1?n-1:Math.floor(n);Va=l.Sd?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Va??0,q=Wa.Yd??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(Na,0)}else if(g())if(Xa=Xa+1|0,1==Ka&&1<La&&0!=Xa%La)I();else{0==Ka&&(Oa=performance.now());a:if(!p){for(l of Ya)if(!1===l())break a;Ja(a);for(n of Za)n()}g()&&I()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),I());if(c)throw"unwind";},Ma=!1,I=null,Sa=0,H=null,Ta=0,Ka=0,La=0,Xa=
0,Ua=[],Ya=[],Za=[];function ab(){I=null;Sa++}var bb=0;function Pa(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bb)bb=b+1E3/60;else for(;b+2>=bb;)bb+=1E3/60;setTimeout(a,Math.max(bb-b,0))}}var Wa={},Oa,Na,Qa,Va,cb=[0,globalThis.document??0,globalThis.window??0],J=a=>{a=2<a?a?C(v,a):"":a;return cb[a]||globalThis.document?.querySelector(a)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],K=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};
function gb(a){var b=L.Nc[a];b.target.removeEventListener(b.Mc,b.vd,b.Qc);L.Nc.splice(a,1)}function hb(){if(navigator.userActivation?navigator.userActivation.isActive:L.gd&&L.Jd.cd){var a=L.Vc;L.Vc=[];for(var b of a)b.kd(...b.rd)}}function M(a){if(!a.target)return-4;if(a.Oc)a.vd=function(c){++L.gd;L.Jd=a;hb();a.Sc(c);hb();--L.gd},a.target.addEventListener(a.Mc,a.vd,a.Qc),L.Nc.push(a);else for(var b=0;b<L.Nc.length;++b)L.Nc[b].target==a.target&&L.Nc[b].Mc==a.Mc&&gb(b--);return 0}
function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={Qd:0,be:0,hd:0,ad:0,od:0,md:0,dd:0,Wd:0,fe:0,Vd:0,ed:0,jd:0,oe:0,ld:0,he(){for(;L.Nc.length;)gb(L.Nc.length-1);L.Vc=[]},gd:0,Vc:[],Ud(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of L.Vc)if(e.kd==a&&d(e.rd,c))return;L.Vc.push({kd:a,zd:b,rd:c});L.Vc.sort((g,f)=>g.zd-f.zd)},je(a){L.Vc=L.Vc.filter(b=>b.kd!=a)},Nc:[],ie:(a,b)=>{for(var c=0;c<L.Nc.length;++c)L.Nc[c].target!=a||b&&b!=L.Nc[c].Mc||gb(c--)},ke(a){let b=!1;for(let c=0;c<
L.Nc.length;++c){const d=L.Nc[c];d.target===a.target&&d.Pc===a.Pc&&d.Oc===a.Oc&&d.Rc===a.Rc&&(gb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},jb=(a,b,c,d,e,g)=>{L.dd||(L.dd=N(256));a={target:J(a),Mc:g,Pc:e,Rc:b,Oc:d,Sc:f=>{var l=f.target.id?f.target.id:"",n=L.dd;G(ib(f.target),n+0,128);G(l,n+128,128);K(d)(e,n,b)&&f.preventDefault()},Qc:c};return M(a)},kb=(a,b,c,d,e)=>{L.ed||(L.ed=N(276));return M({target:a,Mc:e,Pc:19,Rc:b,Oc:d,
Sc:g=>{var f=L.ed,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;t[f]=n;t[f+1]=L.fullscreenEnabled();var q=n?l:L.Nd,u=q?.id||"";G(ib(q),f+2,128);G(u,f+130,128);w[f+260>>2]=q?q.clientWidth:0;w[f+264>>2]=q?q.clientHeight:0;w[f+268>>2]=screen.width;w[f+272>>2]=screen.height;n&&(L.Nd=l);K(d)(19,f,b)&&g.preventDefault()},Qc:c})},lb=(a,b,c,d,e,g)=>{L.hd||(L.hd=N(160));a={target:J(a),
Mc:g,Pc:e,Rc:b,Oc:d,Sc:f=>{var l=L.hd;z[l>>3]=f.timeStamp;var n=l>>2;w[n+2]=f.location;t[l+12]=f.ctrlKey;t[l+13]=f.shiftKey;t[l+14]=f.altKey;t[l+15]=f.metaKey;t[l+16]=f.repeat;w[n+5]=f.charCode;w[n+6]=f.keyCode;w[n+7]=f.which;G(f.key||"",l+32,32);G(f.code||"",l+64,32);G(f.char||"",l+96,32);G(f.locale||"",l+128,32);K(d)(e,l,b)&&f.preventDefault()},Qc:c};return M(a)},mb=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+
25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=db(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,g)=>{L.ad||(L.ad=N(64));a=J(a);return M({target:a,cd:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Mc:g,Pc:e,Rc:b,Oc:d,Sc:f=>{mb(L.ad,f,a);K(d)(e,L.ad,b)&&f.preventDefault()},Qc:c})},ob=(a,b,c,d)=>{L.jd||(L.jd=N(257));return M({target:a,Mc:"pointerlockchange",Pc:20,Rc:b,Oc:d,Sc:e=>{var g=
L.jd,f=document.pointerLockElement;t[g]=!!f;var l=f?.id||"";G(ib(f),g+1,128);G(l,g+129,128);K(d)(20,g,b)&&e.preventDefault()},Qc:c})},pb=(a,b,c,d)=>M({target:a,Mc:"pointerlockerror",Pc:38,Rc:b,Oc:d,Sc:e=>{K(d)(38,0,b)&&e.preventDefault()},Qc:c}),qb=(a,b,c,d)=>{L.md||(L.md=N(36));a=J(a);return M({target:a,Mc:"resize",Pc:10,Rc:b,Oc:d,Sc:e=>{if(e.target==a){var g=document.body;if(g){var f=L.md;w[f>>2]=0;w[f+4>>2]=g.clientWidth;w[f+8>>2]=g.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+
20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset|0;w[f+32>>2]=pageYOffset|0;K(d)(10,f,b)&&e.preventDefault()}}},Qc:c})},rb=(a,b,c,d,e,g)=>{L.ld||(L.ld=N(1552));a=J(a);return M({target:a,cd:"touchstart"==g||"touchend"==g,Mc:g,Pc:e,Rc:b,Oc:d,Sc:f=>{var l={},n=f.touches;for(var q of n)q.wd=q.yd=0,l[q.identifier]=q;for(var u of f.changedTouches)u.wd=1,l[u.identifier]=u;for(var E of f.targetTouches)l[E.identifier].yd=1;n=L.ld;z[n>>3]=f.timeStamp;t[n+12]=f.ctrlKey;t[n+13]=f.shiftKey;t[n+
14]=f.altKey;t[n+15]=f.metaKey;q=n+16;u=db(a);E=0;for(let F of Object.values(l))if(l=q>>2,w[l]=F.identifier,w[l+1]=F.screenX,w[l+2]=F.screenY,w[l+3]=F.clientX,w[l+4]=F.clientY,w[l+5]=F.pageX,w[l+6]=F.pageY,t[q+28]=F.wd,t[q+29]=F.yd,w[l+8]=F.clientX-(u.left|0),w[l+9]=F.clientY-(u.top|0),q+=48,31<++E)break;w[n+8>>2]=E;K(d)(e,n,b)&&f.preventDefault()},Qc:c})},O,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,P=[],Q=[],xb=[],yb=[],R=[],S=[],zb=[],Ab=[],T=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Eb(d);g?(g.name=f,d[f]=g):U||=1282;w[b+4*e>>2]=f}},Gb=(a,b)=>{a.qd||(a.qd=a.getContext,a.getContext=function(d,e){e=a.qd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.xd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.xd,pd:a};a.canvas&&(a.canvas.Od=d);Ab[c]=d;if("undefined"==typeof b.ud||b.ud)if((a=d)||(a=W),!a.Md){a.Md=!0;b=a.pd;b.ee=b.getExtension("WEBGL_multi_draw");b.$d=b.getExtension("EXT_polygon_offset_clamp");b.Zd=b.getExtension("EXT_clip_control");b.pe=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Xd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ce=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.td=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.td)b.td=b.getExtension("EXT_disjoint_timer_query");for(var e of vb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},U,W,Hb=(a,b,c,d,e,g)=>{a={target:J(a),Mc:g,Pc:e,Rc:b,Oc:d,Sc:f=>{K(d)(e,0,b)&&f.preventDefault()},Qc:c};M(a)},Ib=(a,b,c,d)=>{L.od||(L.od=N(96));return M({target:a,cd:!0,Mc:"wheel",Pc:9,Rc:b,Oc:d,Sc:e=>{var g=L.od;mb(g,e,a);z[g+64>>3]=e.deltaX;z[g+72>>3]=e.deltaY;z[g+
80>>3]=e.deltaZ;w[g+88>>2]=e.deltaMode;K(d)(9,g,b)&&e.preventDefault()},Qc:c})},Jb=["default","low-power","high-performance"],Kb={},Mb=()=>{if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Lb=c}return Lb},Lb,Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ob=[null,[],[]],Pb=[],Qb=()=>{var a=vb(O);return a=a.concat(a.map(b=>"GL_"+b))},Rb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){U||=1282;return}c=Qb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else U||=1281},Sb=a=>{var b=Nb(a)+1,c=N(b);c&&G(a,c,b);return c},Tb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ub=a=>{a-=5120;return 0==a?t:1==a?v:2==a?pa:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==
a?x:qa},X=a=>{var b=O.Kd;if(b){var c=b.Xc[a];"number"==typeof c&&(b.Xc[a]=c=O.getUniformLocation(b,b.Hd[a]+(0<c?`[${c}]`:"")));return c}U||=1282},Y=[],Vb=[],Xb=a=>{var b=Nb(a)+1,c=Wb(b);G(a,c,b);return c},$b=a=>{var b=Yb();a();Zb(b)};h.requestAnimationFrame=Pa;h.pauseMainLoop=ab;h.resumeMainLoop=function(){Sa++;var a=Ka,b=La,c=H;H=null;$a(c,0,!1,Ta,!0);Ra(a,b);I()};h.preMainLoop&&Ya.push(h.preMainLoop);h.postMainLoop&&Za.push(h.postMainLoop);for(let a=0;32>a;++a)Pb.push(Array(a));
for(var ac=new Float32Array(288),Z=0;288>=Z;++Z)Y[Z]=ac.subarray(0,Z);var bc=new Int32Array(288);for(Z=0;288>=Z;++Z)Vb[Z]=bc.subarray(0,Z);h.noExitRuntime&&(Ba=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
var N,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,Zb,Wb,Yb,oa,fb,rc={pa:function(){return 0},pb:function(){return 0},qb:function(){},vb:()=>ra(""),ib:()=>{Ba=!1;Da=0},kb:function(a){var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0);if(isNaN(b.getTime()))a=-1;else{var c=w[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),f=Math.min(g,e);0>c?w[a+32>>2]=Number(e!=g&&f==d):0<c!=
(f==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?f:e)-d)));w[a+24>>2]=b.getDay();c=b.getFullYear();w[a+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Fa:Ea)[b.getMonth()]+b.getDate()-1|0;w[a>>2]=b.getSeconds();w[a+4>>2]=b.getMinutes();w[a+8>>2]=b.getHours();w[a+12>>2]=b.getDate();w[a+16>>2]=b.getMonth();w[a+20>>2]=b.getYear();a=b.getTime()/1E3}return BigInt(a)},fb:(a,b)=>{D[a]&&(clearTimeout(D[a].id),delete D[a]);if(!b)return 0;var c=setTimeout(()=>{delete D[a];Ja(()=>qc(a,performance.now()))},b);
D[a]={id:c,ne:b};return 0},lb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=60*Math.max(g,e);w[b>>2]=Number(g!=e);b=f=>{var l=Math.abs(f);return`UTC${0<=f?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(G(a,c,17),G(b,d,17)):(G(a,d,17),G(b,c,17))},xb:function(a){if(void 0===window.localStorage)return 0;a=a?C(v,a):"";return(a=window.localStorage.getItem(a))?Sb(a):
0},yb:function(a,b){void 0!==window.localStorage&&(a=a?C(v,a):"",b=b?C(v,b):"",window.localStorage.setItem(a,b))},Ta:()=>{ab();H=null},ub:()=>Date.now(),ia:()=>globalThis.devicePixelRatio??1,ka:(a,b,c)=>{a=J(a);if(!a)return-4;a=db(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},Ua:()=>performance.now(),Za:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},gb:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),R:(a,b,c,d)=>{if(!L.fullscreenEnabled())return-1;a=J(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},aa:(a,b,c,d)=>lb(a,b,c,d,
2,"keydown"),_:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),_a:(a,b,c)=>{a=K(a);$a(a,b,c)},ga:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?ob(a,b,c,d):-4:-1,U:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?pb(a,b,c,d):-4:-1,ja:(a,b,c,d)=>qb(a,b,c,d),W:(a,b,c,
d)=>rb(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},P:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,Ya:(a,b)=>{var c=b>>2;b={alpha:!!t[b+0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:Jb[w[c+
2]],failIfMajorPerformanceCaveat:!!t[b+12],xd:w[c+4],de:w[c+5],ud:t[b+24],Ld:t[b+25],ge:w[c+7],le:t[b+32]};a=J(a);return!a||b.Ld?0:Gb(a,b)},Xa:a=>{W=Ab[a];h.ctx=O=W?.pd;return!a||O?0:-5},rb:(a,b)=>{var c=0,d=0,e;for(e of Mb()){var g=b+c;x[a+d>>2]=g;c+=G(e,g,Infinity)+1;d+=4}return 0},tb:(a,b)=>{var c=Mb();x[a>>2]=c.length;a=0;for(var d of c)a+=Nb(d)+1;x[b>>2]=a;return 0},lc:a=>{r=a;Ha(a)},oa:()=>52,ob:()=>52,mb:function(){return 70},nb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=x[b>>2],l=x[b+4>>2];
b+=8;for(var n=0;n<l;n++){var q=a,u=v[f+n],E=Ob[q];0===u||10===u?((1===q?ma:k)(C(E)),E.length=0):E.push(u)}e+=l}x[d>>2]=e;return 0},wb:function(a,b,c,d){const e=a?C(v,a):"";console.log("fs_js_save_snapshot: called with",e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(f){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+f);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");
const f=g.result.transaction(["store"],"readwrite");var l=f.objectStore("store");const n=e+"_"+b;l=l.put(v.subarray(c,c+d),n);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",n,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};f.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},o:a=>O.activeTexture(a),C:(a,b)=>{O.attachShader(Q[a],S[b])},a:(a,b)=>{35051==a?
O.sd=b:35052==a&&(O.Wc=b);O.bindBuffer(a,P[b])},w:(a,b,c)=>{O.bindBufferBase(a,b,P[c])},Rb:(a,b,c,d,e)=>{O.bindBufferRange(a,b,P[c],d,e)},i:(a,b)=>{O.bindFramebuffer(a,xb[b])},_b:(a,b)=>{O.bindRenderbuffer(a,yb[b])},n:(a,b)=>{O.bindSampler(a,T[b])},c:(a,b)=>{O.bindTexture(a,R[b])},O:a=>{O.bindVertexArray(zb[a])},J:(a,b,c,d)=>O.blendColor(a,b,c,d),K:(a,b)=>O.blendEquationSeparate(a,b),L:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),Ab:(a,b,c,d,e,g,f,l,n,q)=>O.blitFramebuffer(a,b,c,d,e,g,f,l,n,q),Ga:(a,b,
c,d)=>{2<=W.version?c&&b?O.bufferData(a,v,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?v.subarray(c,c+b):b,d)},D:(a,b,c,d)=>{2<=W.version?c&&O.bufferSubData(a,b,v,d,c):O.bufferSubData(a,b,v.subarray(d,d+c))},Yb:a=>O.checkFramebufferStatus(a),Xb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),ta:(a,b,c)=>{O.clearBufferfv(a,b,y,c>>2)},Wb:(a,b,c)=>{O.clearBufferiv(a,b,w,c>>2)},p:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},cc:a=>{O.compileShader(S[a])},u:(a,b,c,d,e,g,f,l,n)=>{2<=W.version?O.Wc||!l?O.compressedTexSubImage2D(a,
b,c,d,e,g,f,l,n):O.compressedTexSubImage2D(a,b,c,d,e,g,f,v,n,l):O.compressedTexSubImage2D(a,b,c,d,e,g,f,v.subarray(n,n+l))},Ca:(a,b,c,d,e,g,f,l,n,q,u)=>{O.Wc?O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,q,u):O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,v,u,q)},ic:()=>{var a=Eb(Q),b=O.createProgram();b.name=a;b.$c=b.Yc=b.Zc=0;b.nd=1;Q[a]=b;return a},ec:a=>{var b=Eb(S);S[b]=O.createShader(a);return b},G:a=>O.cullFace(a),Ka:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=P[d];e&&(O.deleteBuffer(e),e.name=
0,P[d]=null,d==O.sd&&(O.sd=0),d==O.Wc&&(O.Wc=0))}},v:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=xb[d];e&&(O.deleteFramebuffer(e),e.name=0,xb[d]=null)}},m:a=>{if(a){var b=Q[a];b?(O.deleteProgram(b),b.name=0,Q[a]=null):U||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=yb[d];e&&(O.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=T[d];e&&(O.deleteSampler(e),e.name=0,T[d]=null)}},r:a=>{if(a){var b=S[a];b?(O.deleteShader(b),S[a]=null):U||=
1281}},j:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=R[d];e&&(O.deleteTexture(e),e.name=0,R[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];O.deleteVertexArray(zb[d]);zb[d]=null}},y:a=>O.depthFunc(a),x:a=>{O.depthMask(!!a)},d:a=>O.disable(a),M:a=>{O.disableVertexAttribArray(a)},Cb:(a,b,c)=>{O.drawArrays(a,b,c)},Eb:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},ua:(a,b)=>{for(var c=Pb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];O.drawBuffers(c)},Fb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},Gb:(a,b,c,
d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},g:a=>O.enable(a),Sb:a=>{O.enableVertexAttribArray(a)},k:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,yb[d])},e:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,R[d],e)},A:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,R[c],d,e)},H:a=>O.frontFace(a),Ha:(a,b)=>{V(a,b,"createBuffer",P)},N:(a,b)=>{V(a,b,"createFramebuffer",xb)},$b:(a,b)=>{V(a,b,"createRenderbuffer",yb)},jc:(a,b)=>{V(a,b,"createSampler",T)},Fa:(a,b)=>{V(a,b,"createTexture",R)},Sa:(a,b)=>{V(a,b,"createVertexArray",
zb)},ac:(a,b)=>O.getAttribLocation(Q[a],b?C(v,b):""),b:(a,b)=>Rb(a,b),hc:(a,b,c,d)=>{a=O.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(w[c>>2]=b)},xa:(a,b,c)=>{if(c)if(a>=wb)U||=1281;else if(a=Q[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.$c){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.$c=Math.max(a.$c,O.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.$c}else if(35722==b){if(!a.Yc)for(d=
O.getProgramParameter(a,35721),b=0;b<d;++b)a.Yc=Math.max(a.Yc,O.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.Yc}else if(35381==b){if(!a.Zc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Zc=Math.max(a.Zc,O.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Zc}else w[c>>2]=O.getProgramParameter(a,b);else U||=1281},bc:(a,b,c,d)=>{a=O.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(w[c>>2]=b)},va:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),
w[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(S[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=O.getShaderParameter(S[a],b):U||=1281},Pa:(a,b)=>{if(2>W.version)return U||=1282,0;var c=Bb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Qb().map(Sb),c=Bb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},wa:(a,b)=>{b=b?C(v,b):"";if(a=Q[a]){var c=a,d=c.Xc,e=c.Id,g;if(!d){c.Xc=d={};c.Hd={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,
g);var n=l.name;l=l.size;var q=Tb(n);q=0<q?n.slice(0,q):n;var u=c.nd;c.nd+=l;e[q]=[l,u];for(n=0;n<l;++n)d[u]=n,c.Hd[u++]=q}}c=a.Xc;d=0;e=b;g=Tb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Id[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else U||=1281;return-1},zb:(a,b,c)=>{for(var d=Pb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];O.invalidateFramebuffer(a,d)},ya:a=>{a=Q[a];O.linkProgram(a);a.Xc=0;a.Id={}},Qa:(a,b)=>{3317==a?Cb=b:3314==a&&(Db=b);O.pixelStorei(a,b)},I:(a,
b)=>O.polygonOffset(a,b),Bb:a=>O.readBuffer(a),Zb:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),za:(a,b,c)=>{O.samplerParameterf(T[a],b,c)},f:(a,b,c)=>{O.samplerParameteri(T[a],b,c)},q:(a,b,c,d)=>O.scissor(a,b,c,d),dc:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=x[c+4*g>>2])?C(v,f,d?x[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(S[a],e)},Oa:(a,b,c)=>O.stencilFunc(a,b,c),ra:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),s:a=>O.stencilMask(a),Na:(a,b,c)=>O.stencilOp(a,b,c),qa:(a,b,c,d)=>O.stencilOpSeparate(a,
b,c,d),Ea:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Da:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),t:(a,b,c,d,e,g,f,l,n)=>{if(2<=W.version){if(O.Wc){O.texSubImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var q=Ub(l);O.texSubImage2D(a,b,c,d,e,g,f,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=Ub(l);var u=g*((Db||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*q.BYTES_PER_ELEMENT+Cb-1&-Cb);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=
null;O.texSubImage2D(a,b,c,d,e,g,f,l,n)},Ba:(a,b,c,d,e,g,f,l,n,q,u)=>{if(O.Wc)O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,u);else if(u){var E=Ub(q);O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,E,u>>>31-Math.clz32(E.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,g,f,l,n,q,null)},Qb:(a,b,c)=>{if(2<=W.version)b&&O.uniform1fv(X(a),y,c>>2,b);else{if(288>=b)for(var d=Y[b],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);O.uniform1fv(X(a),d)}},fc:(a,b)=>{O.uniform1i(X(a),b)},Lb:(a,b,c)=>{if(2<=W.version)b&&
O.uniform1iv(X(a),w,c>>2,b);else{if(288>=b)for(var d=Vb[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);O.uniform1iv(X(a),d)}},Pb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2fv(X(a),y,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Y[b],e=0;e<b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2]}else d=y.subarray(c>>2,c+8*b>>2);O.uniform2fv(X(a),d)}},Kb:(a,b,c)=>{if(2<=W.version)b&&O.uniform2iv(X(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Vb[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=
w.subarray(c>>2,c+8*b>>2);O.uniform2iv(X(a),d)}},Nb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3fv(X(a),y,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Y[b],e=0;e<b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2]}else d=y.subarray(c>>2,c+12*b>>2);O.uniform3fv(X(a),d)}},Jb:(a,b,c)=>{if(2<=W.version)b&&O.uniform3iv(X(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Vb[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);O.uniform3iv(X(a),
d)}},Mb:(a,b,c)=>{if(2<=W.version)b&&O.uniform4fv(X(a),y,c>>2,4*b);else{if(72>=b){var d=Y[4*b],e=y;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);O.uniform4fv(X(a),d)}},Ib:(a,b,c)=>{if(2<=W.version)b&&O.uniform4iv(X(a),w,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Vb[b],e=0;e<b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2]}else d=w.subarray(c>>2,c+16*b>>2);O.uniform4iv(X(a),
d)}},Hb:(a,b,c,d)=>{if(2<=W.version)b&&O.uniformMatrix4fv(X(a),!!c,y,d>>2,16*b);else{if(18>=b){var e=Y[16*b],g=y;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(X(a),!!c,e)}},l:a=>{a=Q[a];O.useProgram(a);O.Kd=a},Tb:(a,
b)=>{O.vertexAttribDivisor(a,b)},Ub:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Vb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,e,g)},h:(a,b,c,d)=>O.viewport(a,b,c,d),hb:Ha,db:function(){h.Ad=a=>{0!=dc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Ad)},Wa:function(){h.Gd=a=>{const b=a.clipboardData.getData("text");$b(()=>{const c=Xb(b);cc(c)})};window.addEventListener("paste",h.Gd)},Ma:function(){h.me=[];h.Bd=b=>{b.stopPropagation();b.preventDefault()};
h.Cd=b=>{b.stopPropagation();b.preventDefault()};h.Dd=b=>{b.stopPropagation();b.preventDefault()};h.Ed=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Fd=c;ec(c.length);for(let e=0;e<c.length;e++)$b(()=>{const g=Xb(c[e].name);fc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);gc(b.clientX,b.clientY,d)};const a=h.Tc;a.addEventListener("dragenter",h.Bd,!1);a.addEventListener("dragleave",h.Cd,!1);a.addEventListener("dragover",h.Dd,!1);
a.addEventListener("drop",h.Ed,!1)},Db:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ob:function(a){h.bd&&(URL.revokeObjectURL(h.bd[a].Rd),h.bd[a]=null)},La:function(a){const b=h.Fd;return 0>a||a>=b.length?0:b[a].size},Ia:function(a,b,c,d,e){const g=new FileReader;g.onload=f=>{f=f.target.result;f.byteLength>d?hc(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(f),c),hc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{hc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.Fd[a])},
gc:function(a,b){0!==b&&(document.title=b?C(v,b):"");a=a?C(v,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?cb[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Tc=J(a);h.Tc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Tc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},$a:function(){window.removeEventListener("beforeunload",h.Ad)},Va:function(){window.removeEventListener("paste",h.Gd)},
kc:function(){const a=h.Tc;a.removeEventListener("dragenter",h.Bd);a.removeEventListener("dragleave",h.Cd);a.removeEventListener("dragover",h.Dd);a.removeEventListener("drop",h.Ed)},B:function(){h.Tc&&h.Tc.requestPointerLock&&h.Tc.requestPointerLock()},sa:function(a,b,c){if(h.Tc){if(0===b)a="none";else if(0!=c)a=h.bd[a].Td;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";
break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Tc.style.cursor=a}},sb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(v.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Ra:function(a){a=a?C(v,
a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ab:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=
b.value[0],d=b.value[1];$b(()=>{const e=Xb(c),g=Xb(d);kc(e,g)})}},cb:function(){return h.Uc?h.Uc.bufferSize:0},jb:function(a,b,c){h.Lc=null;h.Uc=null;"undefined"!==typeof AudioContext?h.Lc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.Lc=null,console.log("sokol_audio.h: no WebAudio support"));if(h.Lc){console.log("sokol_audio.h: sample rate ",h.Lc.sampleRate);h.Uc=h.Lc.createScriptProcessor(c,0,b);h.Uc.onaudioprocess=e=>{const g=e.outputBuffer.length,f=jc(g);if(f){const l=e.outputBuffer.numberOfChannels;
for(let n=0;n<l;n++){const q=e.outputBuffer.getChannelData(n);for(let u=0;u<g;u++)q[u]=y[(f>>2)+(l*u+n)]}}};h.Uc.connect(h.Lc.destination);const d=()=>{if(h.Lc){const e=h.Lc.state;"suspended"!==e&&"interrupted"!==e||h.Lc.resume().catch(()=>{console.warn("sokol_audio.h: webaudio resume failed")})}};h.Lc.onstatechange=d;document.addEventListener("visibilitychange",()=>{"visible"===document.visibilityState&&d()});document.addEventListener("click",d,{once:!0});document.addEventListener("touchend",d,{once:!0});
document.addEventListener("keydown",d,{once:!0});return 1}return 0},eb:function(){return h.Lc?h.Lc.sampleRate:0},na:function(){const a=h.Lc;null!==a&&(h.Uc&&h.Uc.disconnect(),a.close(),h.Lc=null,h.Uc=null)},bb:function(){if(h.Lc){const a=h.Lc.state;return"suspended"===a||"interrupted"===a?1:0}return 0},z:function(a,b,c,d,e,g){const f=b?C(v,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=
g?(v.set(n,e),mc(a,d,n.length)):oc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);pc(a)}):nc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);pc(a)})},ma:function(a,b){const c=b?C(v,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),pc(a)):lc(a,Number(d))):nc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,
d);pc(a)})},Aa:function(){return navigator.userAgent.includes("Macintosh")?1:0},la:function(a,b){b=b?C(v,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function sc(a=[]){var b=ic;a.unshift(ea);var c=a.length,d=Wb(4*(c+1)),e=d,g;for(g of a)x[e>>2]=Xb(g),e+=4;x[e>>2]=0;try{var f=b(c,d);r=f;Ha(f)}catch(l){Ga(l)}}
function tc(a=da){function b(){h.calledRun=!0;if(!p){uc.nc();h.onRuntimeInitialized?.();h.noInitialRun||sc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ya.push(c)}xa(ya)}}if(0<A)B=tc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();xa(za);0<A?B=tc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var uc;
(async function(){function a(c){c=uc=c.exports;N=c.oc;cc=h.__sapp_emsc_onpaste=c.pc;dc=h.__sapp_html5_get_ask_leave_site=c.qc;ec=h.__sapp_emsc_begin_drop=c.rc;fc=h.__sapp_emsc_drop=c.sc;gc=h.__sapp_emsc_end_drop=c.tc;hc=h.__sapp_emsc_invoke_fetch_cb=c.uc;h.__sapp_emsc_set_fullscreen_flag=c.vc;ic=h._main=c.wc;jc=h.__saudio_emsc_pull=c.xc;kc=h.__sargs_add_kvp=c.yc;lc=h.__sfetch_emsc_head_response=c.zc;mc=h.__sfetch_emsc_get_response=c.Ac;nc=h.__sfetch_emsc_failed_http_status=c.Bc;oc=h.__sfetch_emsc_failed_buffer_too_small=
c.Cc;pc=h.__sfetch_emsc_failed_other=c.Dc;h._fs_emsc_alloc=c.Ec;h._fs_emsc_load_snapshot_callback=c.Fc;qc=c.Hc;Zb=c.Ic;Wb=c.Jc;Yb=c.Kc;oa=c.mc;fb=c.Gc;na();A--;h.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return uc}A++;h.monitorRunDependencies?.(A);var b={a:rc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=h.locateFile?h.locateFile("raw-ui.wasm",ia):ia+"raw-ui.wasm";return a((await va(b)).instance)})();tc();
