var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,x,y;
function ra(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function sa(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.push(a)},Ca=!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Da)return Da.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,
c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ea=0,Fa=[0,31,60,91,121,152,182,213,244,274,305,335],Ga=[0,31,59,90,120,151,181,212,243,273,304,334],C={},Ha=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Ia=a=>{na=a;Ca||0<Ea||(h.onExit?.(a),q=!0);fa(a,new xa(a))},Ja=a=>{na=a;Ia(a)},Ka=()=>{if(!(Ca||0<Ea))try{var a=na;na=a;Ia(a)}catch(b){Ha(b)}},La=a=>{if(!q)try{a(),Ka()}catch(b){Ha(b)}},D=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=
a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Sa=(a,b)=>{Ma=a;Na=b;if(G)if(Oa||=!0,0==a)H=function(){setTimeout(I,Math.max(0,Pa+b-performance.now())|0)};else if(1==a)H=function(){Qa(I)};else if(2==a){if("undefined"==typeof Ra)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ra=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ra=setImmediate;H=function(){Ra(I)}}},ab=(a,b,c,d,e)=>{function f(){return g<Ta?(Ka(),!1):!0}G=a;Ua=d;var g=Ta;Oa=!1;I=function(){if(!q)if(0<Va.length){var l=Va.shift();
l.Qd(l.Fd);if(Wa){var n=Wa,p=0==n%1?n-1:Math.floor(n);Wa=l.Hd?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Wa??0,p=Xa.Md??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(I,0)}else if(f())if(Ya=Ya+1|0,1==Ma&&1<Na&&0!=Ya%Na)H();else{0==Ma&&(Pa=performance.now());a:if(!q){for(l of Za)if(!1===l())break a;La(a);for(n of $a)n()}f()&&H()}};e||(0<b?Sa(0,1E3/b):Sa(1,1),H());if(c)throw"unwind";},Oa=!1,H=null,Ta=0,G=
null,Ua=0,Ma=0,Na=0,Ya=0,Va=[],Za=[],$a=[];function bb(){H=null;Ta++}var cb=0;function Qa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===cb)cb=b+1E3/60;else for(;b+2>=cb;)cb+=1E3/60;setTimeout(a,Math.max(cb-b,0))}}
var Xa={},Pa,I,Ra,Wa,db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?B(t,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,K=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=L.Ic[a];b.target.removeEventListener(b.Hc,b.md,b.Jc);L.Ic.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:L.Xc&&L.Ad.Vc){var a=L.Oc;L.Oc=[];for(var b of a)b.$c(...b.hd)}}function M(a){if(!a.target)return-4;if(a.Kc)a.md=function(c){++L.Xc;L.Ad=a;ib();a.Lc(c);ib();--L.Xc},a.target.addEventListener(a.Hc,a.md,a.Jc),L.Ic.push(a);else for(var b=0;b<L.Ic.length;++b)L.Ic[b].target==a.target&&L.Ic[b].Hc==a.Hc&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={Gd:0,Rd:0,Yc:0,Uc:0,dd:0,bd:0,Wc:0,Kd:0,Wd:0,Jd:0,Pd:0,Zc:0,de:0,ad:0,Td(a,b,c){r.set(r.subarray(b,b+c),a)},Yd(){for(;L.Ic.length;)hb(L.Ic.length-1);L.Oc=[]},Xc:0,Oc:[],Id(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of L.Oc)if(e.$c==a&&d(e.hd,c))return;L.Oc.push({$c:a,qd:b,hd:c});L.Oc.sort((f,g)=>f.qd<g.qd)},$d(a){L.Oc=L.Oc.filter(b=>b.$c!=a)},Ic:[],Zd:(a,b)=>{for(var c=0;c<L.Ic.length;++c)L.Ic[c].target!=a||b&&b!=L.Ic[c].Hc||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},kb=(a,b,c,d,e,f)=>{L.Wc||(L.Wc=N(256));a={target:J(a),Hc:f,Kc:d,Lc:(g=event)=>{var l=g.target.id?g.target.id:"",n=L.Wc;D(jb(g.target),n+0,128);D(l,n+128,128);K(d)(e,n,b)&&g.preventDefault()},Jc:c};return M(a)},lb=(a,b,c,d,e,f)=>{L.Yc||(L.Yc=N(160));a={target:J(a),Hc:f,Kc:d,Lc:g=>{var l=L.Yc;y[l>>3]=g.timeStamp;var n=l>>2;v[n+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=
g.metaKey;r[l+16]=g.repeat;v[n+5]=g.charCode;v[n+6]=g.keyCode;v[n+7]=g.which;D(g.key||"",l+32,32);D(g.code||"",l+64,32);D(g.char||"",l+96,32);D(g.locale||"",l+128,32);K(d)(e,l,b)&&g.preventDefault()},Jc:c};return M(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=eb(c);v[d+10]=b.clientX-
(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,f)=>{L.Uc||(L.Uc=N(64));a=J(a);return M({target:a,Vc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Hc:f,Kc:d,Lc:(g=event)=>{mb(L.Uc,g,a);K(d)(e,L.Uc,b)&&g.preventDefault()},Jc:c})},ob=(a,b,c,d)=>{L.Zc||(L.Zc=N(257));return M({target:a,Hc:"pointerlockchange",Kc:d,Lc:(e=event)=>{var f=L.Zc,g=document.pointerLockElement;r[f]=!!g;var l=g?.id||"";D(jb(g),f+1,128);D(l,f+129,128);K(d)(20,f,b)&&e.preventDefault()},Jc:c})},pb=(a,b,c,d)=>M({target:a,
Hc:"pointerlockerror",Kc:d,Lc:(e=event)=>{K(d)(38,0,b)&&e.preventDefault()},Jc:c}),qb=(a,b,c,d)=>{L.bd||(L.bd=N(36));a=J(a);return M({target:a,Hc:"resize",Kc:d,Lc:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=L.bd;v[g>>2]=0;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>2]=pageYOffset|0;K(d)(10,g,b)&&e.preventDefault()}}},Jc:c})},rb=(a,b,c,d,e,f)=>{L.ad||(L.ad=
N(1552));a=J(a);return M({target:a,Vc:"touchstart"==f||"touchend"==f,Hc:f,Kc:d,Lc:g=>{var l={},n=g.touches;for(var p of n)p.nd=p.pd=0,l[p.identifier]=p;for(var u of g.changedTouches)u.nd=1,l[u.identifier]=u;for(var E of g.targetTouches)l[E.identifier].pd=1;n=L.ad;y[n>>3]=g.timeStamp;r[n+12]=g.ctrlKey;r[n+13]=g.shiftKey;r[n+14]=g.altKey;r[n+15]=g.metaKey;p=n+16;u=eb(a);E=0;for(let F of Object.values(l))if(l=p>>2,v[l]=F.identifier,v[l+1]=F.screenX,v[l+2]=F.screenY,v[l+3]=F.clientX,v[l+4]=F.clientY,
v[l+5]=F.pageX,v[l+6]=F.pageY,r[p+28]=F.nd,r[p+29]=F.pd,v[l+8]=F.clientX-(u.left|0),v[l+9]=F.clientY-(u.top|0),p+=48,31<++E)break;v[n+8>>2]=E;K(d)(e,n,b)&&g.preventDefault()},Jc:c})},O,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");
b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,xb=[],P=[],yb=[],zb=[],Q=[],R=[],Ab=[],Bb=[],S=[],Cb={},Db=4,Eb=0,Fb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=O[c](),g=f&&Fb(d);f?(f.name=g,d[g]=f):T||=1282;v[b+4*e>>2]=g}},Hb=(a,b)=>{a.gd||(a.gd=a.getContext,a.getContext=function(d,e){e=a.gd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.od?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Gb(c,b):0},Gb=(a,b)=>{var c=Fb(Bb),d={handle:c,attributes:b,version:b.od,ed:a};a.canvas&&(a.canvas.Ed=d);Bb[c]=d;("undefined"==typeof b.ld||b.ld)&&Ib(d);return c},Ib=a=>{a||=V;if(!a.Dd){a.Dd=!0;var b=a.ed;b.Vd=b.getExtension("WEBGL_multi_draw");b.Od=b.getExtension("EXT_polygon_offset_clamp");b.Nd=b.getExtension("EXT_clip_control");b.ee=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Ld=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Sd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.kd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.kd)b.kd=b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Jb=(a,b,c,d,e,f)=>{a={target:J(a),Hc:f,Kc:d,Lc:(g=event)=>{K(d)(e,0,b)&&g.preventDefault()},Jc:c};M(a)},Kb=(a,b,c,d)=>{L.dd||(L.dd=N(96));return M({target:a,Vc:!0,Hc:"wheel",Kc:d,Lc:(e=event)=>{var f=L.dd;mb(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;
v[f+88>>2]=e.deltaMode;K(d)(9,f,b)&&e.preventDefault()},Jc:c})},Lb=["default","low-power","high-performance"],Mb={},Ob=()=>{if(!Nb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Mb)void 0===Mb[b]?delete a[b]:a[b]=Mb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nb=c}return Nb},Nb,Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=
d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Qb=[null,[],[]],Rb=[],Sb=()=>{var a=vb(O);return a=a.concat(a.map(b=>"GL_"+b))},Tb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Sb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=O.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Ub=a=>{var b=Pb(a)+1,c=N(b);c&&D(a,c,b);return c},Vb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Wb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:qa},W=a=>{var b=O.Bd;if(b){var c=b.Qc[a];"number"==typeof c&&(b.Qc[a]=c=O.getUniformLocation(b,b.yd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Xb=[],Zb=a=>{var b=Pb(a)+1,c=Yb(b);D(a,c,b);return c},bc=a=>{var b=$b();a();ac(b)};h.requestAnimationFrame=Qa;h.pauseMainLoop=bb;h.resumeMainLoop=function(){Ta++;var a=Ma,b=Na,c=G;G=null;ab(c,0,!1,Ua,!0);Sa(a,b);H()};h.preMainLoop&&Za.push(h.preMainLoop);h.postMainLoop&&$a.push(h.postMainLoop);for(let a=0;32>a;++a)Rb.push(Array(a));
for(var cc=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=cc.subarray(0,Y);var dc=new Int32Array(288);for(Y=0;288>=Y;++Y)Xb[Y]=dc.subarray(0,Y);h.noExitRuntime&&(Ca=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);
var N,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,ac,Yb,$b,tc={la:function(){return 0},sb:function(){return 0},tb:function(){},xb:()=>sa(""),jb:()=>{Ca=!1;Ea=0},mb:function(a){var b=new Date(v[a+20>>2]+1900,v[a+16>>2],v[a+12>>2],v[a+8>>2],v[a+4>>2],v[a>>2],0),c=v[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?v[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+
6E4*((0<c?g:e)-d)));v[a+24>>2]=b.getDay();c=b.getFullYear();v[a+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ga:Fa)[b.getMonth()]+b.getDate()-1|0;v[a>>2]=b.getSeconds();v[a+4>>2]=b.getMinutes();v[a+8>>2]=b.getHours();v[a+12>>2]=b.getDate();v[a+16>>2]=b.getMonth();v[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},kb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];La(()=>sc(a,performance.now()))},b);C[a]={id:c,ce:b};return 0},nb:(a,b,
c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();w[a>>2]=60*Math.max(f,e);v[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(D(a,c,17),D(b,d,17)):(D(a,d,17),D(b,c,17))},fb:function(a){if(void 0===window.localStorage)return 0;a=a?B(t,a):"";return(a=window.localStorage.getItem(a))?Ub(a):0},gc:function(a,b){void 0!==window.localStorage&&
(a=a?B(t,a):"",b=b?B(t,b):"",window.localStorage.setItem(a,b))},Va:()=>{bb();G=null},wb:()=>Date.now(),ea:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ga:(a,b,c)=>{a=J(a);if(!a)return-4;a=eb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Wa:()=>performance.now(),$a:(a,b)=>{function c(d){K(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},lb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},O:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),da:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},P:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),Y:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),W:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),X:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=K(a);ab(a,b,c)},ca:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),$:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),
_:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),aa:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ba:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),R:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?ob(a,b,c,d):-4:-1,Q:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?pb(a,b,c,d):-4:-1,fa:(a,b,c,d)=>qb(a,b,c,d),S:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),T:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),U:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),V:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),N:(a,b,c,d)=>{Jb(a,b,c,d,31,"webglcontextlost");
return 0},M:(a,b,c,d)=>{Jb(a,b,c,d,32,"webglcontextrestored");return 0},Z:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Kb(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Lb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],od:v[c+4],Ud:v[c+5],ld:r[b+24],Cd:r[b+25],Xd:v[c+7],ae:r[b+32]};a=J(a);return!a||b.Cd?0:Hb(a,b)},Za:a=>{V=Bb[a];h.ctx=O=V?.ed;return!a||O?0:-5},
ub:(a,b)=>{var c=0,d=0,e;for(e of Ob()){var f=b+c;w[a+d>>2]=f;c+=D(e,f,Infinity)+1;d+=4}return 0},vb:(a,b)=>{var c=Ob();w[a>>2]=c.length;a=0;for(var d of c)a+=Pb(d)+1;w[b>>2]=a;return 0},hc:Ja,ka:()=>52,qb:()=>52,ob:function(){return 70},pb:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=a,u=t[g+n],E=Qb[p];0===u||10===u?((1===p?ma:k)(B(E)),E.length=0):E.push(u)}e+=l}w[d>>2]=e;return 0},bb:function(a,b,c,d){const e=a?B(t,a):"";console.log("fs_js_save_snapshot: called with",
e,b);let f;try{f=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}f.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");f.result.createObjectStore("store")};f.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const g=f.result.transaction(["store"],"readwrite");var l=g.objectStore("store");const n=e+"_"+b;l=l.put(t.subarray(c,c+d),n);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",n,"successfully stored")};
l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",n)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};f.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},q:a=>O.activeTexture(a),A:(a,b)=>{O.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?O.jd=b:35052==a&&(O.Pc=b);O.bindBuffer(a,xb[b])},a:(a,b,c)=>{O.bindBufferBase(a,b,xb[c])},n:(a,b)=>{O.bindFramebuffer(a,yb[b])},Ga:(a,b)=>{O.bindRenderbuffer(a,zb[b])},p:(a,b)=>{O.bindSampler(a,S[b])},d:(a,
b)=>{O.bindTexture(a,Q[b])},L:a=>{O.bindVertexArray(Ab[a])},H:(a,b,c,d)=>O.blendColor(a,b,c,d),I:(a,b)=>O.blendEquationSeparate(a,b),J:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),zb:(a,b,c,d,e,f,g,l,n,p)=>O.blitFramebuffer(a,b,c,d,e,f,g,l,n,p),Ja:(a,b,c,d)=>{2<=V.version?c&&b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},B:(a,b,c,d)=>{2<=V.version?c&&O.bufferSubData(a,b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},ra:a=>O.checkFramebufferStatus(a),Vb:(a,b,c,d)=>
O.clearBufferfi(a,b,c,d),pa:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Ub:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},r:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Zb:a=>{O.compileShader(R[a])},Ba:(a,b,c,d,e,f,g,l,n)=>{2<=V.version?O.Pc||!l?O.compressedTexSubImage2D(a,b,c,d,e,f,g,l,n):O.compressedTexSubImage2D(a,b,c,d,e,f,g,t,n,l):O.compressedTexSubImage2D(a,b,c,d,e,f,g,t.subarray(n,n+l))},Aa:(a,b,c,d,e,f,g,l,n,p,u)=>{O.Pc?O.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,p,u):O.compressedTexSubImage3D(a,b,c,d,e,
f,g,l,n,t,u,p)},dc:()=>{var a=Fb(P),b=O.createProgram();b.name=a;b.Tc=b.Rc=b.Sc=0;b.cd=1;P[a]=b;return a},$b:a=>{var b=Fb(R);R[b]=O.createShader(a);return b},E:a=>O.cullFace(a),Ma:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xb[d];e&&(O.deleteBuffer(e),e.name=0,xb[d]=null,d==O.jd&&(O.jd=0),d==O.Pc&&(O.Pc=0))}},g:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=yb[d];e&&(O.deleteFramebuffer(e),e.name=0,yb[d]=null)}},l:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},C:(a,
b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zb[d];e&&(O.deleteRenderbuffer(e),e.name=0,zb[d]=null)}},h:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(O.deleteSampler(e),e.name=0,S[d]=null)}},t:a=>{if(a){var b=R[a];b?(O.deleteShader(b),R[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(O.deleteTexture(e),e.name=0,Q[d]=null)}},La:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];O.deleteVertexArray(Ab[d]);Ab[d]=null}},w:a=>O.depthFunc(a),v:a=>{O.depthMask(!!a)},
e:a=>O.disable(a),K:a=>{O.disableVertexAttribArray(a)},Cb:(a,b,c)=>{O.drawArrays(a,b,c)},Db:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},qa:(a,b)=>{for(var c=Rb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},Eb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},Fb:(a,b,c,d,e)=>{O.drawElementsInstanced(a,b,c,d,e)},j:a=>O.enable(a),Pb:a=>{O.enableVertexAttribArray(a)},sa:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,zb[d])},o:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,Q[d],e)},z:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,
b,Q[c],d,e)},F:a=>O.frontFace(a),Ka:(a,b)=>{U(a,b,"createBuffer",xb)},ta:(a,b)=>{U(a,b,"createFramebuffer",yb)},Ha:(a,b)=>{U(a,b,"createRenderbuffer",zb)},ec:(a,b)=>{U(a,b,"createSampler",S)},Ea:(a,b)=>{U(a,b,"createTexture",Q)},Ua:(a,b)=>{U(a,b,"createVertexArray",Ab)},Xb:(a,b)=>O.getAttribLocation(P[a],b?B(t,b):""),c:(a,b)=>Tb(a,b),cc:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},wa:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=P[a],35716==
b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Tc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Tc=Math.max(a.Tc,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Tc}else if(35722==b){if(!a.Rc)for(d=O.getProgramParameter(a,35721),b=0;b<d;++b)a.Rc=Math.max(a.Rc,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Rc}else if(35381==b){if(!a.Sc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Sc=Math.max(a.Sc,O.getActiveUniformBlockName(a,
b).length+1);v[c>>2]=a.Sc}else v[c>>2]=O.getProgramParameter(a,b);else T||=1281},Yb:(a,b,c,d)=>{a=O.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(v[c>>2]=b)},ua:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(R[a],b):T||=1281},Sa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Cb[a];if(c)return 0>b||b>=c.length?(T||=1281,
0):c[b];switch(a){case 7939:return c=Sb().map(Ub),c=Cb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},va:(a,b)=>{b=b?B(t,b):"";if(a=P[a]){var c=a,d=c.Qc,e=c.zd,f;if(!d){c.Qc=d={};c.yd={};var g=O.getProgramParameter(c,35718);for(f=0;f<g;++f){var l=O.getActiveUniform(c,f);var n=l.name;l=l.size;var p=Vb(n);p=0<p?n.slice(0,p):n;var u=c.cd;c.cd+=l;e[p]=[l,u];for(n=0;n<l;++n)d[u]=n,c.yd[u++]=p}}c=a.Qc;d=0;e=b;f=Vb(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.zd[e])&&
d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else T||=1281;return-1},yb:(a,b,c)=>{for(var d=Rb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,d)},xa:a=>{a=P[a];O.linkProgram(a);a.Qc=0;a.zd={}},Ta:(a,b)=>{3317==a?Db=b:3314==a&&(Eb=b);O.pixelStorei(a,b)},G:(a,b)=>O.polygonOffset(a,b),Bb:a=>O.readBuffer(a),Fa:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),ya:(a,b,c)=>{O.samplerParameterf(S[a],b,c)},i:(a,b,c)=>{O.samplerParameteri(S[a],b,c)},s:(a,b,c,d)=>O.scissor(a,
b,c,d),_b:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=w[c+4*f>>2])?B(t,g,d?w[d+4*f>>2]:void 0):"";e+=g}O.shaderSource(R[a],e)},Qa:(a,b,c)=>O.stencilFunc(a,b,c),oa:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),u:a=>O.stencilMask(a),Pa:(a,b,c)=>O.stencilOp(a,b,c),na:(a,b,c,d)=>O.stencilOpSeparate(a,b,c,d),Da:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ca:(a,b,c,d,e,f)=>O.texStorage3D(a,b,c,d,e,f),f:(a,b,c,d,e,f,g,l,n)=>{if(2<=V.version){if(O.Pc){O.texSubImage2D(a,b,c,d,e,f,g,l,n);return}if(n){var p=Wb(l);
O.texSubImage2D(a,b,c,d,e,f,g,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Wb(l);var u=f*((Eb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*p.BYTES_PER_ELEMENT+Db-1&-Db);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;O.texSubImage2D(a,b,c,d,e,f,g,l,n)},za:(a,b,c,d,e,f,g,l,n,p,u)=>{if(O.Pc)O.texSubImage3D(a,b,c,d,e,f,g,l,n,p,u);else if(u){var E=Wb(p);O.texSubImage3D(a,b,c,d,e,f,g,l,n,p,E,u>>>
31-Math.clz32(E.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,f,g,l,n,p,null)},Ob:(a,b,c)=>{if(2<=V.version)b&&O.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(W(a),d)}},ac:(a,b)=>{O.uniform1i(W(a),b)},Kb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Xb[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(W(a),d)}},Nb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2fv(W(a),
x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(W(a),d)}},Jb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Xb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);O.uniform2iv(W(a),d)}},Mb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+
(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(W(a),d)}},Ib:(a,b,c)=>{if(2<=V.version)b&&O.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Xb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(W(a),d)}},Lb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+
3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(W(a),d)}},Hb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Xb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(W(a),d)}},Gb:(a,b,c,d)=>{if(2<=V.version)b&&O.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],f=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+
2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=P[a];O.useProgram(a);O.Bd=a},Qb:(a,b)=>{O.vertexAttribDivisor(a,b)},Rb:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Sb:(a,b,c,d,e,f)=>{O.vertexAttribPointer(a,b,c,!!d,e,f)},m:(a,b,c,d)=>O.viewport(a,b,c,d),ib:Ia,Ya:function(){h.rd=
a=>{0!=fc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.rd)},Ra:function(){h.xd=a=>{const b=a.clipboardData.getData("text");bc(()=>{const c=Zb(b);ec(c)})};window.addEventListener("paste",h.xd)},Ia:function(){h.be=[];h.sd=b=>{b.stopPropagation();b.preventDefault()};h.td=b=>{b.stopPropagation();b.preventDefault()};h.ud=b=>{b.stopPropagation();b.preventDefault()};h.vd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.wd=c;gc(c.length);for(let e=
0;e<c.length;e++)bc(()=>{const f=Zb(c[e].name);hc(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ic(b.clientX,b.clientY,d)};const a=h.Mc;a.addEventListener("dragenter",h.sd,!1);a.addEventListener("dragleave",h.td,!1);a.addEventListener("dragover",h.ud,!1);a.addEventListener("drop",h.vd,!1)},rb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},fc:function(a){const b=h.wd;return 0>a||a>=b.length?0:b[a].size},bc:function(a,
b,c,d,e){const f=new FileReader;f.onload=g=>{g=g.target.result;g.byteLength>d?jc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),jc(a,1,0,b,g.byteLength,c,d,e))};f.onerror=()=>{jc(a,0,2,b,0,c,d,e)};f.readAsArrayBuffer(h.wd[a])},Tb:function(a,b){0!==b&&(document.title=b?B(t,b):"");a=a?B(t,a):"";void 0!==h.canvas&&("object"===typeof h.canvas?db[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Mc=J(a);h.Mc||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);h.Mc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Xa:function(){window.removeEventListener("beforeunload",h.rd)},Oa:function(){window.removeEventListener("paste",h.xd)},Wb:function(){const a=h.Mc;a.removeEventListener("dragenter",h.sd);a.removeEventListener("dragleave",h.td);a.removeEventListener("dragover",h.ud);a.removeEventListener("drop",h.vd)},y:function(){h.Mc&&h.Mc.requestPointerLock&&h.Mc.requestPointerLock()},Ab:function(a,b){if(h.Mc){if(0===
b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Mc.style.cursor=a}},hb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(t.subarray(c,
c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Na:function(a){a=a?B(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();
document.execCommand("copy");document.body.removeChild(b)},cb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];bc(()=>{const e=Zb(c),f=Zb(d);mc(e,f)})}},db:function(){return h.Nc?h.Nc.bufferSize:0},gb:function(a,b,c){h.Gc=null;h.Nc=null;"undefined"!==typeof AudioContext?h.Gc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.Gc=null,console.log("sokol_audio.h: no WebAudio support"));return h.Gc?
(console.log("sokol_audio.h: sample rate ",h.Gc.sampleRate),h.Nc=h.Gc.createScriptProcessor(c,0,b),h.Nc.onaudioprocess=d=>{const e=d.outputBuffer.length,f=lc(e);if(f){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=x[(f>>2)+(g*p+l)]}}},h.Nc.connect(h.Gc.destination),a=()=>{h.Gc&&"suspended"===h.Gc.state&&h.Gc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",
a,{once:!0}),1):0},eb:function(){return h.Gc?h.Gc.sampleRate:0},ja:function(){const a=h.Gc;null!==a&&(h.Nc&&h.Nc.disconnect(),a.close(),h.Gc=null,h.Nc=null)},x:function(a,b,c,d,e,f){const g=b?B(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(g,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=f?(t.set(n,e),oc(a,d,n.length)):qc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,n);rc(a)}):pc(a,l.status)}).catch(l=>
{console.error(`sokol_fetch.h: GET ${g} failed with: `,l);rc(a)})},ia:function(a,b){const c=b?B(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),rc(a)):nc(a,Number(d))):pc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);rc(a)})},ma:function(){return navigator.userAgent.includes("Macintosh")?1:0},ha:function(a,b){b=b?B(t,b):"";switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.ic;ra();gb=Z.Bc;c=Z;N=c.kc;h._fs_emsc_alloc=c.lc;h._fs_emsc_load_snapshot_callback=c.mc;h.__sapp_emsc_onpaste=ec=c.nc;h.__sapp_html5_get_ask_leave_site=fc=c.oc;h.__sapp_emsc_begin_drop=gc=c.pc;h.__sapp_emsc_drop=hc=c.qc;h.__sapp_emsc_end_drop=ic=c.rc;h.__sapp_emsc_invoke_fetch_cb=jc=c.sc;h._main=kc=c.tc;h.__saudio_emsc_pull=lc=c.uc;h.__sargs_add_kvp=mc=c.vc;h.__sfetch_emsc_head_response=nc=c.wc;h.__sfetch_emsc_get_response=oc=c.xc;h.__sfetch_emsc_failed_http_status=
pc=c.yc;h.__sfetch_emsc_failed_buffer_too_small=qc=c.zc;h.__sfetch_emsc_failed_other=rc=c.Ac;sc=c.Cc;ac=c.Dc;Yb=c.Ec;$b=c.Fc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:tc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile("raw-ui.wasm",ia):ia+"raw-ui.wasm";return a((await wa(b)).instance)})();
function uc(a=[]){var b=kc;a.unshift(ea);var c=a.length,d=Yb(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Zb(g);e+=4});w[e>>2]=0;try{var f=b(c,d);Ja(f,!0)}catch(g){Ha(g)}}
function vc(a=da){function b(){h.calledRun=!0;if(!q){Z.jc();h.onRuntimeInitialized?.();h.noInitialRun||uc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=vc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=vc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();vc();
