var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,x,y;
function ra(){var a=oa.buffer;r=new Int8Array(a);pa=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var z=0,A=null;function sa(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(h)},za=[],Aa=[],Ba=()=>{var a=h.preRun.shift();Aa.push(a)},Ca=!0,Da=0,Ea=[0,31,60,91,121,152,182,213,244,274,305,335],Fa=[0,31,59,90,120,151,181,212,243,273,304,334],B={},Ga=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Ha=a=>{na=a;Ca||0<Da||(h.onExit?.(a),q=!0);fa(a,new xa(a))},Ia=a=>{na=a;Ha(a)},Ja=()=>{if(!(Ca||0<Da))try{var a=na;na=a;Ha(a)}catch(b){Ga(b)}},Ka=a=>{if(!q)try{a(),Ja()}catch(b){Ga(b)}},E=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=
0;g<a.length;++g){var f=a.codePointAt(g);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},Ra=(a,b)=>{La=a;Ma=b;if(F)if(Na||=!0,0==a)G=function(){setTimeout(H,Math.max(0,Oa+b-performance.now())|0)};else if(1==a)G=function(){Pa(H)};else if(2==a){if("undefined"==
typeof Qa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qa=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qa=setImmediate;G=function(){Qa(H)}}},$a=(a,b,c,d,e)=>{function g(){return f<Sa?(Ja(),!1):!0}F=a;Ta=d;var f=Sa;Na=!1;H=function(){if(!q)if(0<Ua.length){var l=
Ua.shift();l.Ed(l.td);if(Va){var n=Va,p=0==n%1?n-1:Math.floor(n);Va=l.vd?p:(8*n+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Va??0,p=Wa.Ad??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(H,0)}else if(g())if(Xa=Xa+1|0,1==La&&1<Ma&&0!=Xa%Ma)G();else{0==La&&(Oa=performance.now());a:if(!q){for(l of Ya)if(!1===l())break a;Ka(a);for(n of Za)n()}g()&&G()}};e||(0<b?Ra(0,1E3/b):Ra(1,1),G());if(c)throw"unwind";},Na=!1,G=
null,Sa=0,F=null,Ta=0,La=0,Ma=0,Xa=0,Ua=[],Ya=[],Za=[];function ab(){G=null;Sa++}var bb=0;function Pa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===bb)bb=b+1E3/60;else for(;b+2>=bb;)bb+=1E3/60;setTimeout(a,Math.max(bb-b,0))}}
var Wa={},Oa,H,Qa,Va,cb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,I=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&cb)return cb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
db=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?I(t,a):"":a;return db[a]||("undefined"!=typeof document?document.querySelector(a):null)},eb=a=>0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},fb=[],gb,K=a=>{var b=fb[a];b||(fb[a]=b=gb.get(a));return b};function hb(a){var b=L.wc[a];b.target.removeEventListener(b.vc,b.Yc,b.xc);L.wc.splice(a,1)}
function ib(){if(navigator.userActivation?navigator.userActivation.isActive:L.Lc&&L.od.Jc){var a=L.Bc;L.Bc=[];for(var b of a)b.Oc(...b.Uc)}}function M(a){if(!a.target)return-4;if(a.yc)a.Yc=function(c){++L.Lc;L.od=a;ib();a.zc(c);ib();--L.Lc},a.target.addEventListener(a.vc,a.Yc,a.xc),L.wc.push(a);else for(var b=0;b<L.wc.length;++b)L.wc[b].target==a.target&&L.wc[b].vc==a.vc&&hb(b--);return 0}function jb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var L={ud:0,Fd:0,Mc:0,Ic:0,Sc:0,Qc:0,Kc:0,yd:0,Kd:0,xd:0,Dd:0,Nc:0,Sd:0,Pc:0,Hd(a,b,c){r.set(r.subarray(b,b+c),a)},Md(){for(;L.wc.length;)hb(L.wc.length-1);L.Bc=[]},Lc:0,Bc:[],wd(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l in g)if(g[l]!=f[l])return!1;return!0}for(var e of L.Bc)if(e.Oc==a&&d(e.Uc,c))return;L.Bc.push({Oc:a,bd:b,Uc:c});L.Bc.sort((g,f)=>g.bd<f.bd)},Od(a){L.Bc=L.Bc.filter(b=>b.Oc!=a)},wc:[],Nd:(a,b)=>{for(var c=0;c<L.wc.length;++c)L.wc[c].target!=a||b&&b!=L.wc[c].vc||
hb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},kb=(a,b,c,d,e,g)=>{L.Kc||(L.Kc=N(256));a={target:J(a),vc:g,yc:d,zc:(f=event)=>{var l=f.target.id?f.target.id:"",n=L.Kc;E(jb(f.target),n+0,128);E(l,n+128,128);K(d)(e,n,b)&&f.preventDefault()},xc:c};return M(a)},lb=(a,b,c,d,e,g)=>{L.Mc||(L.Mc=N(160));a={target:J(a),vc:g,yc:d,zc:f=>{var l=L.Mc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=
f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;E(f.key||"",l+32,32);E(f.code||"",l+64,32);E(f.char||"",l+96,32);E(f.locale||"",l+128,32);K(d)(e,l,b)&&f.preventDefault()},xc:c};return M(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=eb(c);v[d+10]=b.clientX-
(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,g)=>{L.Ic||(L.Ic=N(64));a=J(a);return M({target:a,Jc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,vc:g,yc:d,zc:(f=event)=>{mb(L.Ic,f,a);K(d)(e,L.Ic,b)&&f.preventDefault()},xc:c})},ob=(a,b,c,d)=>{L.Nc||(L.Nc=N(257));return M({target:a,vc:"pointerlockchange",yc:d,zc:(e=event)=>{var g=L.Nc,f=document.pointerLockElement;r[g]=!!f;var l=f?.id||"";E(jb(f),g+1,128);E(l,g+129,128);K(d)(20,g,b)&&e.preventDefault()},xc:c})},pb=(a,b,c,d)=>M({target:a,
vc:"pointerlockerror",yc:d,zc:(e=event)=>{K(d)(38,0,b)&&e.preventDefault()},xc:c}),qb=(a,b,c,d)=>{L.Qc||(L.Qc=N(36));a=J(a);return M({target:a,vc:"resize",yc:d,zc:(e=event)=>{if(e.target==a){var g=document.body;if(g){var f=L.Qc;v[f>>2]=0;v[f+4>>2]=g.clientWidth;v[f+8>>2]=g.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;K(d)(10,f,b)&&e.preventDefault()}}},xc:c})},rb=(a,b,c,d,e,g)=>{L.Pc||(L.Pc=
N(1552));a=J(a);return M({target:a,Jc:"touchstart"==g||"touchend"==g,vc:g,yc:d,zc:f=>{var l={},n=f.touches;for(var p of n)p.Zc=p.ad=0,l[p.identifier]=p;for(var u of f.changedTouches)u.Zc=1,l[u.identifier]=u;for(var C of f.targetTouches)l[C.identifier].ad=1;n=L.Pc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;p=n+16;u=eb(a);C=0;for(let D of Object.values(l))if(l=p>>2,v[l]=D.identifier,v[l+1]=D.screenX,v[l+2]=D.screenY,v[l+3]=D.clientX,v[l+4]=D.clientY,
v[l+5]=D.pageX,v[l+6]=D.pageY,r[p+28]=D.Zc,r[p+29]=D.ad,v[l+8]=D.clientX-(u.left|0),v[l+9]=D.clientY-(u.top|0),p+=48,31<++C)break;v[n+8>>2]=C;K(d)(e,n,b)&&f.preventDefault()},xc:c})},O,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");
b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,xb=[],P=[],yb=[],zb=[],Q=[],R=[],Ab=[],Bb=[],S=[],Cb={},Db=4,Eb=0,Fb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=O[c](),f=g&&Fb(d);g?(g.name=f,d[f]=g):T||=1282;v[b+4*e>>2]=f}},Hb=(a,b)=>{a.ld||(a.ld=a.getContext,a.getContext=function(d,e){e=a.ld(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.$c?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Gb(c,b):0},Gb=(a,b)=>{var c=Fb(Bb),d={handle:c,attributes:b,version:b.$c,Tc:a};a.canvas&&(a.canvas.sd=d);Bb[c]=d;("undefined"==typeof b.Xc||b.Xc)&&Ib(d);return c},Ib=a=>{a||=V;if(!a.rd){a.rd=!0;var b=a.Tc;b.Jd=b.getExtension("WEBGL_multi_draw");b.Cd=b.getExtension("EXT_polygon_offset_clamp");b.Bd=b.getExtension("EXT_clip_control");b.Td=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.zd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Gd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Wc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Wc)b.Wc=b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Jb=(a,b,c,d,e,g)=>{a={target:J(a),vc:g,yc:d,zc:(f=event)=>{K(d)(e,0,b)&&f.preventDefault()},xc:c};M(a)},Kb=(a,b,c,d)=>{L.Sc||(L.Sc=N(96));return M({target:a,Jc:!0,vc:"wheel",yc:d,zc:(e=event)=>{var g=L.Sc;mb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;
v[g+88>>2]=e.deltaMode;K(d)(9,g,b)&&e.preventDefault()},xc:c})},Lb=["default","low-power","high-performance"],Mb=[null,[],[]],Nb=[],Ob=()=>{var a=vb(O);return a=a.concat(a.map(b=>"GL_"+b))},Pb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=O.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Ob().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=O.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Rb=a=>{var b=Qb(a)+
1,c=N(b);c&&E(a,c,b);return c},Sb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Tb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},W=a=>{var b=O.pd;if(b){var c=b.Ec[a];"number"==typeof c&&(b.Ec[a]=c=O.getUniformLocation(b,b.md[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Ub=[],Wb=a=>{var b=Qb(a)+1,c=Vb(b);E(a,c,b);return c},Zb=a=>{var b=Xb();a();Yb(b)};h.requestAnimationFrame=Pa;h.pauseMainLoop=ab;
h.resumeMainLoop=function(){Sa++;var a=La,b=Ma,c=F;F=null;$a(c,0,!1,Ta,!0);Ra(a,b);G()};h.preMainLoop&&Ya.push(h.preMainLoop);h.postMainLoop&&Za.push(h.postMainLoop);for(let a=0;32>a;++a)Nb.push(Array(a));for(var $b=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=$b.subarray(0,Y);var ac=new Int32Array(288);for(Y=0;288>=Y;++Y)Ub[Y]=ac.subarray(0,Y);h.noExitRuntime&&(Ca=h.noExitRuntime);h.print&&(ma=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(da=h.arguments);
h.thisProgram&&(ea=h.thisProgram);
var N,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,Yb,Vb,Xb,qc={pb:()=>sa(""),fb:()=>{Ca=!1;Da=0},ib:function(a){var b=new Date(v[a+20>>2]+1900,v[a+16>>2],v[a+12>>2],v[a+8>>2],v[a+4>>2],v[a>>2],0),c=v[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),f=Math.min(g,e);0>c?v[a+32>>2]=Number(e!=g&&f==d):0<c!=(f==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?f:e)-d)));v[a+24>>2]=b.getDay();c=b.getFullYear();
v[a+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Fa:Ea)[b.getMonth()]+b.getDate()-1|0;v[a>>2]=b.getSeconds();v[a+4>>2]=b.getMinutes();v[a+8>>2]=b.getHours();v[a+12>>2]=b.getDate();v[a+16>>2]=b.getMonth();v[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},gb:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ka(()=>pc(a,performance.now()))},b);B[a]={id:c,Rd:b};return 0},jb:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();w[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=f=>{var l=Math.abs(f);return`UTC${0<=f?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(E(a,c,17),E(b,d,17)):(E(a,d,17),E(b,c,17))},Ua:()=>{ab();F=null},ob:()=>Date.now(),fa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=J(a);if(!a)return-4;a=eb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Wa:()=>performance.now(),$a:(a,b)=>{function c(d){K(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},hb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);ra();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},P:(a,b,c,d)=>kb(a,b,c,d,12,"blur"),ea:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>kb(a,b,c,d,13,"focus"),Z:(a,
b,c,d)=>lb(a,b,c,d,2,"keydown"),X:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),Y:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=K(a);$a(a,b,c)},da:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),aa:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),$:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ba:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ca:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?ob(a,b,c,d):-4:-1,R:(a,b,c,d)=>document.body?.requestPointerLock?(a=J(a))?pb(a,b,c,d):-4:-1,ga:(a,b,c,d)=>qb(a,
b,c,d),T:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),W:(a,b,c,d)=>rb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Jb(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Jb(a,b,c,d,32,"webglcontextrestored");return 0},_:(a,b,c,d)=>(a=J(a))?"undefined"!=typeof a.onwheel?Kb(a,b,c,d):-1:-4,_a:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+
5],powerPreference:Lb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],$c:v[c+4],Id:v[c+5],Xc:r[b+24],qd:r[b+25],Ld:v[c+7],Pd:r[b+32]};a=J(a);return!a||b.qd?0:Hb(a,b)},Za:a=>{V=Bb[a];h.ctx=O=V?.Tc;return!a||O?0:-5},Xb:Ia,lb:()=>52,kb:function(){return 70},nb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=a,u=t[f+n],C=Mb[p];0===u||10===u?((1===p?ma:k)(I(C)),C.length=0):C.push(u)}e+=l}w[d>>2]=e;return 0},o:a=>O.activeTexture(a),y:(a,b)=>{O.attachShader(P[a],
R[b])},b:(a,b)=>{35051==a?O.Vc=b:35052==a&&(O.Dc=b);O.bindBuffer(a,xb[b])},a:(a,b,c)=>{O.bindBufferBase(a,b,xb[c])},j:(a,b)=>{O.bindFramebuffer(a,yb[b])},Ga:(a,b)=>{O.bindRenderbuffer(a,zb[b])},n:(a,b)=>{O.bindSampler(a,S[b])},d:(a,b)=>{O.bindTexture(a,Q[b])},M:a=>{O.bindVertexArray(Ab[a])},I:(a,b,c,d)=>O.blendColor(a,b,c,d),J:(a,b)=>O.blendEquationSeparate(a,b),K:(a,b,c,d)=>O.blendFuncSeparate(a,b,c,d),rb:(a,b,c,d,e,g,f,l,n,p)=>O.blitFramebuffer(a,b,c,d,e,g,f,l,n,p),Ia:(a,b,c,d)=>{2<=V.version?c&&
b?O.bufferData(a,t,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?t.subarray(c,c+b):b,d)},C:(a,b,c,d)=>{2<=V.version?c&&O.bufferSubData(a,b,t,d,c):O.bufferSubData(a,b,t.subarray(d,d+c))},qa:a=>O.checkFramebufferStatus(a),Mb:(a,b,c,d)=>O.clearBufferfi(a,b,c,d),na:(a,b,c)=>{O.clearBufferfv(a,b,x,c>>2)},Lb:(a,b,c)=>{O.clearBufferiv(a,b,v,c>>2)},p:(a,b,c,d)=>{O.colorMask(!!a,!!b,!!c,!!d)},Rb:a=>{O.compileShader(R[a])},Aa:(a,b,c,d,e,g,f,l,n)=>{2<=V.version?O.Dc||!l?O.compressedTexSubImage2D(a,b,c,d,e,g,f,
l,n):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t,n,l):O.compressedTexSubImage2D(a,b,c,d,e,g,f,t.subarray(n,n+l))},za:(a,b,c,d,e,g,f,l,n,p,u)=>{O.Dc?O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,p,u):O.compressedTexSubImage3D(a,b,c,d,e,g,f,l,n,t,u,p)},xa:()=>{var a=Fb(P),b=O.createProgram();b.name=a;b.Hc=b.Fc=b.Gc=0;b.Rc=1;P[a]=b;return a},Tb:a=>{var b=Fb(R);R[b]=O.createShader(a);return b},F:a=>O.cullFace(a),Ma:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xb[d];e&&(O.deleteBuffer(e),e.name=0,xb[d]=
null,d==O.Vc&&(O.Vc=0),d==O.Dc&&(O.Dc=0))}},g:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=yb[d];e&&(O.deleteFramebuffer(e),e.name=0,yb[d]=null)}},m:a=>{if(a){var b=P[a];b?(O.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},D:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zb[d];e&&(O.deleteRenderbuffer(e),e.name=0,zb[d]=null)}},r:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(O.deleteSampler(e),e.name=0,S[d]=null)}},q:a=>{if(a){var b=R[a];b?(O.deleteShader(b),R[a]=null):T||=1281}},
E:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(O.deleteTexture(e),e.name=0,Q[d]=null)}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];O.deleteVertexArray(Ab[d]);Ab[d]=null}},v:a=>O.depthFunc(a),u:a=>{O.depthMask(!!a)},e:a=>O.disable(a),L:a=>{O.disableVertexAttribArray(a)},tb:(a,b,c)=>{O.drawArrays(a,b,c)},ub:(a,b,c,d)=>{O.drawArraysInstanced(a,b,c,d)},pa:(a,b)=>{for(var c=Nb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];O.drawBuffers(c)},vb:(a,b,c,d)=>{O.drawElements(a,b,c,d)},wb:(a,b,c,d,e)=>
{O.drawElementsInstanced(a,b,c,d,e)},i:a=>O.enable(a),Gb:a=>{O.enableVertexAttribArray(a)},ra:(a,b,c,d)=>{O.framebufferRenderbuffer(a,b,c,zb[d])},k:(a,b,c,d,e)=>{O.framebufferTexture2D(a,b,c,Q[d],e)},x:(a,b,c,d,e)=>{O.framebufferTextureLayer(a,b,Q[c],d,e)},G:a=>O.frontFace(a),Ja:(a,b)=>{U(a,b,"createBuffer",xb)},sa:(a,b)=>{U(a,b,"createFramebuffer",yb)},Ha:(a,b)=>{U(a,b,"createRenderbuffer",zb)},ya:(a,b)=>{U(a,b,"createSampler",S)},Ea:(a,b)=>{U(a,b,"createTexture",Q)},Ta:(a,b)=>{U(a,b,"createVertexArray",
Ab)},Ob:(a,b)=>O.getAttribLocation(P[a],b?I(t,b):""),c:(a,b)=>Pb(a,b),Vb:(a,b,c,d)=>{a=O.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(v[c>>2]=b)},va:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=P[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Hc){var d=O.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Hc=Math.max(a.Hc,O.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Hc}else if(35722==b){if(!a.Fc)for(d=
O.getProgramParameter(a,35721),b=0;b<d;++b)a.Fc=Math.max(a.Fc,O.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Fc}else if(35381==b){if(!a.Gc)for(d=O.getProgramParameter(a,35382),b=0;b<d;++b)a.Gc=Math.max(a.Gc,O.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Gc}else v[c>>2]=O.getProgramParameter(a,b);else T||=1281},Pb:(a,b,c,d)=>{a=O.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(v[c>>2]=b)},ta:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),
v[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=O.getShaderParameter(R[a],b):T||=1281},Ra:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Cb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Ob().map(Rb),c=Cb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ua:(a,b)=>{b=b?I(t,b):"";if(a=P[a]){var c=a,d=c.Ec,e=c.nd,g;if(!d){c.Ec=d={};c.md={};var f=O.getProgramParameter(c,35718);for(g=0;g<f;++g){var l=O.getActiveUniform(c,
g);var n=l.name;l=l.size;var p=Sb(n);p=0<p?n.slice(0,p):n;var u=c.Rc;c.Rc+=l;e[p]=[l,u];for(n=0;n<l;++n)d[u]=n,c.md[u++]=p}}c=a.Ec;d=0;e=b;g=Sb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.nd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else T||=1281;return-1},qb:(a,b,c)=>{for(var d=Nb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];O.invalidateFramebuffer(a,d)},wa:a=>{a=P[a];O.linkProgram(a);a.Ec=0;a.nd={}},Sa:(a,b)=>{3317==a?Db=b:3314==a&&(Eb=b);O.pixelStorei(a,b)},H:(a,
b)=>O.polygonOffset(a,b),sb:a=>O.readBuffer(a),Fa:(a,b,c,d,e)=>O.renderbufferStorageMultisample(a,b,c,d,e),A:(a,b,c)=>{O.samplerParameterf(S[a],b,c)},h:(a,b,c)=>{O.samplerParameteri(S[a],b,c)},oa:(a,b,c,d)=>O.scissor(a,b,c,d),Sb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=w[c+4*g>>2])?I(t,f,d?w[d+4*g>>2]:void 0):"";e+=f}O.shaderSource(R[a],e)},Pa:(a,b,c)=>O.stencilFunc(a,b,c),ma:(a,b,c,d)=>O.stencilFuncSeparate(a,b,c,d),s:a=>O.stencilMask(a),Oa:(a,b,c)=>O.stencilOp(a,b,c),la:(a,b,c,d)=>O.stencilOpSeparate(a,
b,c,d),Ca:(a,b,c,d,e)=>O.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,g)=>O.texStorage3D(a,b,c,d,e,g),f:(a,b,c,d,e,g,f,l,n)=>{if(2<=V.version){if(O.Dc){O.texSubImage2D(a,b,c,d,e,g,f,l,n);return}if(n){var p=Tb(l);O.texSubImage2D(a,b,c,d,e,g,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Tb(l);var u=g*((Eb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Db-1&-Db);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=
null;O.texSubImage2D(a,b,c,d,e,g,f,l,n)},B:(a,b,c,d,e,g,f,l,n,p,u)=>{if(O.Dc)O.texSubImage3D(a,b,c,d,e,g,f,l,n,p,u);else if(u){var C=Tb(p);O.texSubImage3D(a,b,c,d,e,g,f,l,n,p,C,u>>>31-Math.clz32(C.BYTES_PER_ELEMENT))}else O.texSubImage3D(a,b,c,d,e,g,f,l,n,p,null)},Fb:(a,b,c)=>{if(2<=V.version)b&&O.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);O.uniform1fv(W(a),d)}},Ub:(a,b)=>{O.uniform1i(W(a),b)},Bb:(a,b,c)=>{if(2<=V.version)b&&
O.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Ub[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);O.uniform1iv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&O.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);O.uniform2fv(W(a),d)}},Ab:(a,b,c)=>{if(2<=V.version)b&&O.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Ub[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=
v.subarray(c>>2,c+8*b>>2);O.uniform2iv(W(a),d)}},Db:(a,b,c)=>{if(2<=V.version)b&&O.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);O.uniform3fv(W(a),d)}},zb:(a,b,c)=>{if(2<=V.version)b&&O.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Ub[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);O.uniform3iv(W(a),
d)}},Cb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);O.uniform4fv(W(a),d)}},yb:(a,b,c)=>{if(2<=V.version)b&&O.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Ub[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);O.uniform4iv(W(a),
d)}},xb:(a,b,c,d)=>{if(2<=V.version)b&&O.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],g=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];O.useProgram(a);O.pd=a},Ib:(a,
b)=>{O.vertexAttribDivisor(a,b)},Jb:(a,b,c,d,e)=>{O.vertexAttribIPointer(a,b,c,d,e)},Kb:(a,b,c,d,e,g)=>{O.vertexAttribPointer(a,b,c,!!d,e,g)},t:(a,b,c,d)=>O.viewport(a,b,c,d),eb:Ha,Wb:function(){h.cd=a=>{0!=cc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.cd)},Ya:function(){h.kd=a=>{const b=a.clipboardData.getData("text");Zb(()=>{const c=Wb(b);bc(c)})};window.addEventListener("paste",h.kd)},Va:function(){h.Qd=[];h.dd=b=>{b.stopPropagation();b.preventDefault()};
h.ed=b=>{b.stopPropagation();b.preventDefault()};h.gd=b=>{b.stopPropagation();b.preventDefault()};h.hd=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.jd=c;dc(c.length);for(let e=0;e<c.length;e++)Zb(()=>{const g=Wb(c[e].name);ec(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);fc(b.clientX,b.clientY,d)};const a=h.Cc;a.addEventListener("dragenter",h.dd,!1);a.addEventListener("dragleave",h.ed,!1);a.addEventListener("dragover",h.gd,!1);
a.addEventListener("drop",h.hd,!1)},Qb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Qa:function(a){const b=h.jd;return 0>a||a>=b.length?0:b[a].size},Na:function(a,b,c,d,e){const g=new FileReader;g.onload=f=>{f=f.target.result;f.byteLength>d?gc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(f),c),gc(a,1,0,b,f.byteLength,c,d,e))};g.onerror=()=>{gc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(h.jd[a])},Da:function(a,b){0!==b&&(document.title=b?I(t,b):"");a=a?I(t,
a):"";void 0!==h.canvas&&("object"===typeof h.canvas?db[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Cc=J(a);h.Cc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Cc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},bb:function(){window.removeEventListener("beforeunload",h.cd)},Xa:function(){window.removeEventListener("paste",h.kd)},La:function(){const a=h.Cc;a.removeEventListener("dragenter",
h.dd);a.removeEventListener("dragleave",h.ed);a.removeEventListener("dragover",h.gd);a.removeEventListener("drop",h.hd)},z:function(){h.Cc&&h.Cc.requestPointerLock&&h.Cc.requestPointerLock()},Nb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
cb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Zb(()=>{const e=Wb(c),g=Wb(d);jc(e,g)})}},db:function(){return h.Ac?h.Ac.bufferSize:0},Hb:function(a,b,c){h.uc=null;h.Ac=null;"undefined"!==typeof AudioContext?h.uc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(h.uc=null,console.log("sokol_audio.h: no WebAudio support"));return h.uc?(console.log("sokol_audio.h: sample rate ",h.uc.sampleRate),
h.Ac=h.uc.createScriptProcessor(c,0,b),h.Ac.onaudioprocess=d=>{const e=d.outputBuffer.length,g=ic(e);if(g){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=x[(g>>2)+(f*p+l)]}}},h.Ac.connect(h.uc.destination),a=()=>{h.uc&&"suspended"===h.uc.state&&h.uc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},mb:function(){return h.uc?
h.uc.sampleRate:0},ka:function(){const a=h.uc;null!==a&&(h.Ac&&h.Ac.disconnect(),a.close(),h.uc=null,h.Ac=null)},w:function(a,b,c,d,e,g){const f=b?I(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=g?(t.set(n,e),lc(a,d,n.length)):nc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);oc(a)}):mc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,
l);oc(a)})},ja:function(a,b){const c=b?I(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),oc(a)):kc(a,Number(d))):mc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);oc(a)})},ia:function(a,b){b=b?I(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;oa=Z.Yb;ra();gb=Z.pc;c=Z;N=c._b;h._fs_emsc_alloc=c.$b;h._fs_emsc_load_snapshot_callback=c.ac;h.__sapp_emsc_onpaste=bc=c.bc;h.__sapp_html5_get_ask_leave_site=cc=c.cc;h.__sapp_emsc_begin_drop=dc=c.dc;h.__sapp_emsc_drop=ec=c.ec;h.__sapp_emsc_end_drop=fc=c.fc;h.__sapp_emsc_invoke_fetch_cb=gc=c.gc;h._main=hc=c.hc;h.__saudio_emsc_pull=ic=c.ic;h.__sargs_add_kvp=jc=c.jc;h.__sfetch_emsc_head_response=kc=c.kc;h.__sfetch_emsc_get_response=lc=c.lc;h.__sfetch_emsc_failed_http_status=
mc=c.mc;h.__sfetch_emsc_failed_buffer_too_small=nc=c.nc;h.__sfetch_emsc_failed_other=oc=c.oc;pc=c.qc;Yb=c.rc;Vb=c.sc;Xb=c.tc;z--;h.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;h.monitorRunDependencies?.(z);var b={a:qc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile("raw.wasm",ia):ia+"raw.wasm";return a((await wa(b)).instance)})();
function rc(a=[]){var b=hc;a.unshift(ea);var c=a.length,d=Vb(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Wb(f);e+=4});w[e>>2]=0;try{var g=b(c,d);Ia(g,!0)}catch(f){Ga(f)}}
function sc(a=da){function b(){h.calledRun=!0;if(!q){Z.Zb();h.onRuntimeInitialized?.();h.noInitialRun||rc(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=sc;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();ya(Aa);0<z?A=sc:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();sc();
