var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,l="",ha,ia,ja;
if(fa){var fs=require("fs"),ka=require("path");l=k?ka.dirname(l)+"/":__dirname+"/";ha=(a,b)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ja=a=>{a=ha(a,!0);a.buffer||(a=new Uint8Array(a));return a};ia=(a,b,c,d=!0)=>{a=a.startsWith("file://")?new URL(a):ka.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,h)=>{e?c(e):b(d?h.buffer:h)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=
typeof module&&(module.exports=g);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof la||a.context instanceof la))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",a=>{throw a;});da=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(ea||k)k?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),l=0!==l.indexOf("blob:")?l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+
1):"",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},k&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);
Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var t;g.wasmBinary&&(t=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&na("no native wasm support detected");var oa,pa=!1,qa,v,ra,sa,w,x,y,z;
function ta(){var a=oa.buffer;g.HEAP8=qa=new Int8Array(a);g.HEAP16=ra=new Int16Array(a);g.HEAP32=w=new Int32Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=x=new Uint32Array(a);g.HEAPF32=y=new Float32Array(a);g.HEAPF64=z=new Float64Array(a)}var ua,va=[],wa=[],xa=[],ya=[],za=[];function Aa(){var a=g.preRun.shift();va.unshift(a)}var A=0,Ba=null,B=null;
function na(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";r(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ca(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="raw.wasm";if(!Ca(C)){var Da=C;C=g.locateFile?g.locateFile(Da,l):l+Da}function Ea(a){try{if(a==C&&t)return new Uint8Array(t);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){na(b)}}
function Fa(a){if(!t&&(ea||k)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{r("failed to asynchronously prepare wasm: "+d);na(d)})}
function Ha(a,b){var c=C;t||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||c.startsWith("file://")||fa||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){r("wasm streaming compile failed: "+e);r("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ia(a){for(;0<a.length;)a.shift()(g)}var Ja=[0,31,60,91,121,152,182,213,244,274,305,335],Ka=[0,31,59,90,120,151,181,212,243,273,304,334];function La(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}
function D(a,b,c){var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e}function Ma(a){var b=La(a)+1,c=E(b);c&&D(a,c,b);return c}
function Na(a){var b=Oa();a();Pa(b)}var Qa=0;function Ra(){for(var a=F.length-1;0<=a;--a)Sa(a);F=[];Ta=[]}var Ta=[];function Ua(){if(Qa&&Va.yc)for(var a=0;a<Ta.length;++a){var b=Ta[a];Ta.splice(a,1);--a;b.ld.apply(null,b.$c)}}var F=[];function Sa(a){var b=F[a];b.target.removeEventListener(b.pc,b.Wc,b.qc);F.splice(a,1)}
function G(a){function b(d){++Qa;Va=a;Ua();a.sc(d);Ua();--Qa}if(a.rc)a.Wc=b,a.target.addEventListener(a.pc,b,a.qc),F.push(a),Wa||(ya.push(Ra),Wa=!0);else for(var c=0;c<F.length;++c)F[c].target==a.target&&F[c].pc==a.pc&&Sa(c--)}function Xa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Wa,Va,Ya,Za,$a,ab,bb,cb,db,eb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function fb(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&eb)return eb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function H(a,b){return a?fb(v,a,b):""}
var gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function I(a){a=2<a?H(a):a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function hb(a){return 0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var ib=[];function J(a){var b=ib[a];b||(a>=ib.length&&(ib.length=a+1),ib[a]=b=ua.get(a));return b}
function jb(a,b,c,d,e,h){Ya||(Ya=E(256));a={target:I(a),pc:h,rc:d,sc:function(f=event){var m=f.target.id?f.target.id:"",n=Ya;D(Xa(f.target),n+0,128);D(m,n+128,128);J(d)(e,n,b)&&f.preventDefault()},qc:c};G(a)}
function kb(a,b,c,d,e,h){Za||(Za=E(176));a={target:I(a),yc:!0,pc:h,rc:d,sc:function(f){var m=Za;z[m>>3]=f.timeStamp;var n=m>>2;w[n+2]=f.location;w[n+3]=f.ctrlKey;w[n+4]=f.shiftKey;w[n+5]=f.altKey;w[n+6]=f.metaKey;w[n+7]=f.repeat;w[n+8]=f.charCode;w[n+9]=f.keyCode;w[n+10]=f.which;D(f.key||"",m+44,32);D(f.code||"",m+76,32);D(f.char||"",m+108,32);D(f.locale||"",m+140,32);J(d)(e,m,b)&&f.preventDefault()},qc:c};G(a)}
function lb(a,b,c){z[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;ra[2*a+20]=b.button;ra[2*a+21]=b.buttons;w[a+11]=b.movementX;w[a+12]=b.movementY;c=hb(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top}
function K(a,b,c,d,e,h){$a||($a=E(72));a=I(a);G({target:a,yc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,pc:h,rc:d,sc:function(f=event){lb($a,f,a);J(d)(e,$a,b)&&f.preventDefault()},qc:c})}function mb(a,b,c,d,e){ab||(ab=E(260));G({target:a,pc:e,rc:d,sc:function(h=event){var f=ab,m=document.pointerLockElement||document.vc||document.Lc||document.Kc;w[f>>2]=!!m;var n=m&&m.id?m.id:"";D(Xa(m),f+4,128);D(n,f+132,128);J(d)(20,f,b)&&h.preventDefault()},qc:c})}
function nb(a,b,c,d,e){G({target:a,pc:e,rc:d,sc:function(h=event){J(d)(38,0,b)&&h.preventDefault()},qc:c})}function ob(a,b,c,d){bb||(bb=E(36));a=I(a);G({target:a,pc:"resize",rc:d,sc:function(e=event){if(e.target==a){var h=document.body;if(h){var f=bb;w[f>>2]=e.detail;w[f+4>>2]=h.clientWidth;w[f+8>>2]=h.clientHeight;w[f+12>>2]=innerWidth;w[f+16>>2]=innerHeight;w[f+20>>2]=outerWidth;w[f+24>>2]=outerHeight;w[f+28>>2]=pageXOffset;w[f+32>>2]=pageYOffset;J(d)(10,f,b)&&e.preventDefault()}}},qc:c})}
function pb(a,b,c,d,e,h){cb||(cb=E(1696));a=I(a);G({target:a,yc:"touchstart"==h||"touchend"==h,pc:h,rc:d,sc:function(f){for(var m,n={},p=f.touches,q=0;q<p.length;++q)m=p[q],m.Hc=m.Jc=0,n[m.identifier]=m;for(q=0;q<f.changedTouches.length;++q)m=f.changedTouches[q],m.Hc=1,n[m.identifier]=m;for(q=0;q<f.targetTouches.length;++q)n[f.targetTouches[q].identifier].Jc=1;p=cb;z[p>>3]=f.timeStamp;var u=p>>2;w[u+3]=f.ctrlKey;w[u+4]=f.shiftKey;w[u+5]=f.altKey;w[u+6]=f.metaKey;u+=7;var qb=hb(a),rb=0;for(q in n)if(m=
n[q],w[u]=m.identifier,w[u+1]=m.screenX,w[u+2]=m.screenY,w[u+3]=m.clientX,w[u+4]=m.clientY,w[u+5]=m.pageX,w[u+6]=m.pageY,w[u+7]=m.Hc,w[u+8]=m.Jc,w[u+9]=m.clientX-qb.left,w[u+10]=m.clientY-qb.top,u+=13,31<++rb)break;w[p+8>>2]=rb;J(d)(e,p,b)&&f.preventDefault()},qc:c})}
function sb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,f){b.drawElementsInstancedANGLE(c,d,e,h,f)})}
function tb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ub(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function vb(a){a.bd=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function wb(a){a.dd=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function xb(a){a.gd=a.getExtension("WEBGL_multi_draw")}var yb=1,zb=[],L=[],Ab=[],M=[],N=[],O=[],Bb=[],Cb=[],Db={},Eb=4;function P(a){Fb||(Fb=a)}function Gb(a){for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b}
function Hb(a,b){a.vc||(a.vc=a.getContext,a.getContext=function(d,e){e=a.vc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Ic?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Ib(c,b):0}function Ib(a,b){var c=Gb(Cb),d={cd:c,attributes:b,version:b.Ic,Cc:a};a.canvas&&(a.canvas.Zc=d);Cb[c]=d;("undefined"==typeof b.Gc||b.Gc)&&Jb(d);return c}
function Jb(a){a||(a=Q);if(!a.Yc){a.Yc=!0;var b=a.Cc;sb(b);tb(b);ub(b);vb(b);wb(b);2<=a.version&&(b.Fc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Fc)b.Fc=b.getExtension("EXT_disjoint_timer_query");xb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Fb,Q;function Kb(a,b,c,d,e,h){a={target:I(a),pc:h,rc:d,sc:(f=event)=>{J(d)(e,0,b)&&f.preventDefault()},qc:c};G(a)}
function Lb(a,b,c,d){db||(db=E(104));G({target:a,yc:!0,pc:"wheel",rc:d,sc:function(e=event){var h=db;lb(h,e,a);z[h+72>>3]=e.deltaX;z[h+80>>3]=e.deltaY;z[h+88>>3]=e.deltaZ;w[h+96>>2]=e.deltaMode;J(d)(9,h,b)&&e.preventDefault()},qc:c})}var Mb=["default","low-power","high-performance"];function Nb(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);pa=!0}da(a,new la(a))}var Ob=[null,[],[]],Pb=[];function R(a,b,c,d){for(var e=0;e<a;e++){var h=S[c](),f=h&&Gb(d);h?(h.name=f,d[f]=h):P(1282);w[b+4*e>>2]=f}}
function Qb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Q.version){P(1282);return}c=2*(S.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>Q.version){P(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":P(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:P(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){P(1280);r("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:P(1280);r("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else P(1281)}
function Rb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function T(a){a-=5120;return 0==a?qa:1==a?v:2==a?ra:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:sa}function U(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Sb(a,b,c,d,e){a=T(a);var h=U(a),f=Eb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<h)+f-1&-f)>>h)}
function V(a){var b=S.Vc;if(b){var c=b.xc[a];"number"==typeof c&&(b.xc[a]=c=S.getUniformLocation(b,b.Tc[a]+(0<c?"["+c+"]":"")));return c}P(1282)}var W=[],X=[];function Y(a){var b=La(a)+1,c=Tb(b);D(a,c,b);return c}for(var S,Z=0;32>Z;++Z)Pb.push(Array(Z));var Ub=new Float32Array(288);for(Z=0;288>Z;++Z)W[Z]=Ub.subarray(0,Z+1);var Vb=new Int32Array(288);for(Z=0;288>Z;++Z)X[Z]=Vb.subarray(0,Z+1);
var ic={gb:function(a){var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0),c=w[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),f=Math.min(h,e);0>c?w[a+32>>2]=Number(e!=h&&f==d):0<c!=(f==d)&&(e=Math.max(h,e),b.setTime(b.getTime()+6E4*((0<c?f:e)-d)));w[a+24>>2]=b.getDay();c=b.getFullYear();w[a+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ka:Ja)[b.getMonth()]+b.getDate()-1|0;w[a>>2]=
b.getSeconds();w[a+4>>2]=b.getMinutes();w[a+8>>2]=b.getHours();w[a+12>>2]=b.getDate();w[a+16>>2]=b.getMonth();w[a+20>>2]=b.getYear();return b.getTime()/1E3|0},eb:function(a,b,c){function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),h=new Date(e,0,1),f=new Date(e,6,1);e=h.getTimezoneOffset();var m=f.getTimezoneOffset();x[a>>2]=60*Math.max(e,m);w[b>>2]=Number(e!=m);a=d(h);b=d(f);a=Ma(a);b=Ma(b);m<e?(x[c>>2]=a,x[c+4>>2]=b):(x[c>>2]=b,x[c+4>>2]=
a)},i:function(){na("")},kb:function(){return Date.now()},fa:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},ga:function(a,b,c){a=I(a);if(!a)return-4;a=hb(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},hb:function(a,b,c){v.copyWithin(a,b,b+c)},Ya:function(a,b){function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},db:function(a){var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=
Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var f=oa.buffer;try{oa.grow(h.call(e,2147483648,d)-f.byteLength+65535>>>16);ta();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},P:function(a,b,c,d){jb(a,b,c,d,12,"blur");return 0},ea:function(a,b,c){a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:function(a,b,c,d){jb(a,b,c,d,13,"focus");return 0},Z:function(a,b,c,d){kb(a,b,c,d,2,"keydown");return 0},X:function(a,b,c,d){kb(a,b,c,d,1,"keypress");return 0},Y:function(a,b,c,d){kb(a,
b,c,d,3,"keyup");return 0},da:function(a,b,c,d){K(a,b,c,d,5,"mousedown");return 0},aa:function(a,b,c,d){K(a,b,c,d,33,"mouseenter");return 0},$:function(a,b,c,d){K(a,b,c,d,34,"mouseleave");return 0},ba:function(a,b,c,d){K(a,b,c,d,8,"mousemove");return 0},ca:function(a,b,c,d){K(a,b,c,d,6,"mouseup");return 0},S:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.vc||document.body.Lc||document.body.Kc))return-1;a=I(a);if(!a)return-4;mb(a,b,c,d,"pointerlockchange");
mb(a,b,c,d,"mozpointerlockchange");mb(a,b,c,d,"webkitpointerlockchange");mb(a,b,c,d,"mspointerlockchange");return 0},R:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.vc||document.body.Lc||document.body.Kc))return-1;a=I(a);if(!a)return-4;nb(a,b,c,d,"pointerlockerror");nb(a,b,c,d,"mozpointerlockerror");nb(a,b,c,d,"webkitpointerlockerror");nb(a,b,c,d,"mspointerlockerror");return 0},Za:function(a,b,c,d){ob(a,b,c,d);return 0},T:function(a,b,c,d){pb(a,b,c,d,25,"touchcancel");
return 0},U:function(a,b,c,d){pb(a,b,c,d,23,"touchend");return 0},V:function(a,b,c,d){pb(a,b,c,d,24,"touchmove");return 0},W:function(a,b,c,d){pb(a,b,c,d,22,"touchstart");return 0},O:function(a,b,c,d){Kb(a,b,c,d,31,"webglcontextlost");return 0},N:function(a,b,c,d){Kb(a,b,c,d,32,"webglcontextrestored");return 0},_:function(a,b,c,d){a=I(a);return"undefined"!=typeof a.onwheel?(Lb(a,b,c,d),0):-1},Wa:function(a,b){b>>=2;b={alpha:!!w[b],depth:!!w[b+1],stencil:!!w[b+2],antialias:!!w[b+3],premultipliedAlpha:!!w[b+
4],preserveDrawingBuffer:!!w[b+5],powerPreference:Mb[w[b+6]],failIfMajorPerformanceCaveat:!!w[b+7],Ic:w[b+8],ed:w[b+9],Gc:w[b+10],Xc:w[b+11],hd:w[b+12],jd:w[b+13]};a=I(a);return!a||b.Xc?0:Hb(a,b)},Ua:function(a,b){a=Cb[a];b=H(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&sb(S);"OES_vertex_array_object"==b&&tb(S);"WEBGL_draw_buffers"==b&&ub(S);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&vb(S);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&wb(S);"WEBGL_multi_draw"==
b&&xb(S);return!!a.Cc.getExtension(b)},Xa:function(a){a>>=2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},Va:function(a){Q=Cb[a];g.ad=S=Q&&Q.Cc;return!a||S?0:-5},Sb:Nb,ib:function(){return 52},cb:function(){return 70},jb:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var f=x[b>>2],m=x[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=v[f+n],q=Ob[a];0===p||10===p?((1===a?ma:r)(fb(q,0)),q.length=0):q.push(p)}e+=m}x[d>>2]=e;return 0},f:function(a){S.activeTexture(a)},B:function(a,b){S.attachShader(L[a],
O[b])},b:function(a,b){35051==a?S.Ec=b:35052==a&&(S.uc=b);S.bindBuffer(a,zb[b])},j:function(a,b){S.bindFramebuffer(a,Ab[b])},Ea:function(a,b){S.bindRenderbuffer(a,M[b])},a:function(a,b){S.bindTexture(a,N[b])},K:function(a){S.bindVertexArray(Bb[a])},G:function(a,b,c,d){S.blendColor(a,b,c,d)},H:function(a,b){S.blendEquationSeparate(a,b)},I:function(a,b,c,d){S.blendFuncSeparate(a,b,c,d)},ob:function(a,b,c,d,e,h,f,m,n,p){S.blitFramebuffer(a,b,c,d,e,h,f,m,n,p)},Ga:function(a,b,c,d){2<=Q.version?c&&b?S.bufferData(a,
v,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?v.subarray(c,c+b):b,d)},n:function(a,b,c,d){2<=Q.version?c&&S.bufferSubData(a,b,v,d,c):S.bufferSubData(a,b,v.subarray(d,d+c))},pa:function(a){return S.checkFramebufferStatus(a)},Ib:function(a,b,c,d){S.clearBufferfi(a,b,c,d)},ma:function(a,b,c){S.clearBufferfv(a,b,y,c>>2)},Hb:function(a,b,c){S.clearBufferiv(a,b,w,c>>2)},l:function(a,b,c,d){S.colorMask(!!a,!!b,!!c,!!d)},Nb:function(a){S.compileShader(O[a])},Aa:function(a,b,c,d,e,h,f,m){2<=Q.version?S.uc||
!f?S.compressedTexImage2D(a,b,c,d,e,h,f,m):S.compressedTexImage2D(a,b,c,d,e,h,v,m,f):S.compressedTexImage2D(a,b,c,d,e,h,m?v.subarray(m,m+f):null)},ya:function(a,b,c,d,e,h,f,m,n){S.uc?S.compressedTexImage3D(a,b,c,d,e,h,f,m,n):S.compressedTexImage3D(a,b,c,d,e,h,f,v,n,m)},wa:function(){var a=Gb(L),b=S.createProgram();b.name=a;b.Bc=b.zc=b.Ac=0;b.Dc=1;L[a]=b;return a},Pb:function(a){var b=Gb(O);O[b]=S.createShader(a);return b},D:function(a){S.cullFace(a)},Qa:function(a,b){for(var c=0;c<a;c++){var d=w[b+
4*c>>2],e=zb[d];e&&(S.deleteBuffer(e),e.name=0,zb[d]=null,d==S.Ec&&(S.Ec=0),d==S.uc&&(S.uc=0))}},d:function(a,b){for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Ab[d];e&&(S.deleteFramebuffer(e),e.name=0,Ab[d]=null)}},x:function(a){if(a){var b=L[a];b?(S.deleteProgram(b),b.name=0,L[a]=null):P(1281)}},L:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=M[d];e&&(S.deleteRenderbuffer(e),e.name=0,M[d]=null)}},t:function(a){if(a){var b=O[a];b?(S.deleteShader(b),O[a]=null):P(1281)}},M:function(a,b){for(var c=
0;c<a;c++){var d=w[b+4*c>>2],e=N[d];e&&(S.deleteTexture(e),e.name=0,N[d]=null)}},Oa:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2];S.deleteVertexArray(Bb[d]);Bb[d]=null}},w:function(a){S.depthFunc(a)},v:function(a){S.depthMask(!!a)},e:function(a){S.disable(a)},J:function(a){S.disableVertexAttribArray(a)},rb:function(a,b,c){S.drawArrays(a,b,c)},sb:function(a,b,c,d){S.drawArraysInstanced(a,b,c,d)},oa:function(a,b){for(var c=Pb[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];S.drawBuffers(c)},tb:function(a,b,
c,d){S.drawElements(a,b,c,d)},ub:function(a,b,c,d,e){S.drawElementsInstanced(a,b,c,d,e)},h:function(a){S.enable(a)},Eb:function(a){S.enableVertexAttribArray(a)},qa:function(a,b,c,d){S.framebufferRenderbuffer(a,b,c,M[d])},k:function(a,b,c,d,e){S.framebufferTexture2D(a,b,c,N[d],e)},A:function(a,b,c,d,e){S.framebufferTextureLayer(a,b,N[c],d,e)},E:function(a){S.frontFace(a)},Ha:function(a,b){R(a,b,"createBuffer",zb)},ra:function(a,b){R(a,b,"createFramebuffer",Ab)},Fa:function(a,b){R(a,b,"createRenderbuffer",
M)},Ca:function(a,b){R(a,b,"createTexture",N)},Na:function(a,b){R(a,b,"createVertexArray",Bb)},Lb:function(a,b){return S.getAttribLocation(L[a],H(b))},c:function(a,b){Qb(a,b)},Qb:function(a,b,c,d){a=S.getProgramInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,d,b):0;c&&(w[c>>2]=b)},ua:function(a,b,c){if(c)if(a>=yb)P(1281);else if(a=L[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.Bc)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Bc=
Math.max(a.Bc,S.getActiveUniform(a,b).name.length+1);w[c>>2]=a.Bc}else if(35722==b){if(!a.zc)for(b=0;b<S.getProgramParameter(a,35721);++b)a.zc=Math.max(a.zc,S.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.zc}else if(35381==b){if(!a.Ac)for(b=0;b<S.getProgramParameter(a,35382);++b)a.Ac=Math.max(a.Ac,S.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.Ac}else w[c>>2]=S.getProgramParameter(a,b);else P(1281)},Mb:function(a,b,c,d){a=S.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,
d,b):0;c&&(w[c>>2]=b)},sa:function(a,b,c){c?35716==b?(a=S.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(O[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=S.getShaderParameter(O[a],b):P(1281)},Ra:function(a,b){if(2>Q.version)return P(1282),0;var c=Db[a];if(c)return 0>b||b>=c.length?(P(1281),0):c[b];switch(a){case 7939:return c=S.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Ma(d)}),c=Db[a]=c,
0>b||b>=c.length?(P(1281),0):c[b];default:return P(1280),0}},r:function(a,b){b=H(b);if(a=L[a]){var c=a,d=c.xc,e=c.Uc,h;if(!d)for(c.xc=d={},c.Tc={},h=0;h<S.getProgramParameter(c,35718);++h){var f=S.getActiveUniform(c,h);var m=f.name;f=f.size;var n=Rb(m);n=0<n?m.slice(0,n):m;var p=c.Dc;c.Dc+=f;e[n]=[f,p];for(m=0;m<f;++m)d[p]=m,c.Tc[p++]=n}c=a.xc;d=0;e=b;h=Rb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Uc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else P(1281);
return-1},nb:function(a,b,c){for(var d=Pb[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];S.invalidateFramebuffer(a,d)},va:function(a){a=L[a];S.linkProgram(a);a.xc=0;a.Uc={}},Ma:function(a,b){3317==a&&(Eb=b);S.pixelStorei(a,b)},F:function(a,b){S.polygonOffset(a,b)},pb:function(a){S.readBuffer(a)},Da:function(a,b,c,d,e){S.renderbufferStorageMultisample(a,b,c,d,e)},na:function(a,b,c,d){S.scissor(a,b,c,d)},Ob:function(a,b,c,d){for(var e="",h=0;h<b;++h){var f=d?w[d+4*h>>2]:-1;e+=H(w[c+4*h>>2],0>f?void 0:f)}S.shaderSource(O[a],
e)},Ka:function(a,b,c){S.stencilFunc(a,b,c)},la:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},u:function(a){S.stencilMask(a)},Ja:function(a,b,c){S.stencilOp(a,b,c)},ka:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},za:function(a,b,c,d,e,h,f,m,n){if(2<=Q.version)if(S.uc)S.texImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=T(m);S.texImage2D(a,b,c,d,e,h,f,m,p,n>>U(p))}else S.texImage2D(a,b,c,d,e,h,f,m,null);else S.texImage2D(a,b,c,d,e,h,f,m,n?Sb(m,f,d,e,n):null)},xa:function(a,b,c,d,e,h,f,m,n,p){if(S.uc)S.texImage3D(a,
b,c,d,e,h,f,m,n,p);else if(p){var q=T(n);S.texImage3D(a,b,c,d,e,h,f,m,n,q,p>>U(q))}else S.texImage3D(a,b,c,d,e,h,f,m,n,null)},C:function(a,b,c){S.texParameterf(a,b,c)},g:function(a,b,c){S.texParameteri(a,b,c)},mb:function(a,b,c,d,e,h,f,m,n){if(2<=Q.version)if(S.uc)S.texSubImage2D(a,b,c,d,e,h,f,m,n);else if(n){var p=T(m);S.texSubImage2D(a,b,c,d,e,h,f,m,p,n>>U(p))}else S.texSubImage2D(a,b,c,d,e,h,f,m,null);else p=null,n&&(p=Sb(m,f,e,h,n)),S.texSubImage2D(a,b,c,d,e,h,f,m,p)},lb:function(a,b,c,d,e,h,
f,m,n,p,q){if(S.uc)S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,q);else if(q){var u=T(p);S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,u,q>>U(u))}else S.texSubImage3D(a,b,c,d,e,h,f,m,n,p,null)},Db:function(a,b,c){if(2<=Q.version)b&&S.uniform1fv(V(a),y,c>>2,b);else{if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1fv(V(a),d)}},ta:function(a,b){S.uniform1i(V(a),b)},zb:function(a,b,c){if(2<=Q.version)b&&S.uniform1iv(V(a),w,c>>2,b);else{if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=
w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1iv(V(a),d)}},Cb:function(a,b,c){if(2<=Q.version)b&&S.uniform2fv(V(a),y,c>>2,2*b);else{if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2fv(V(a),d)}},yb:function(a,b,c){if(2<=Q.version)b&&S.uniform2iv(V(a),w,c>>2,2*b);else{if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);S.uniform2iv(V(a),d)}},Bb:function(a,
b,c){if(2<=Q.version)b&&S.uniform3fv(V(a),y,c>>2,3*b);else{if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3fv(V(a),d)}},xb:function(a,b,c){if(2<=Q.version)b&&S.uniform3iv(V(a),w,c>>2,3*b);else{if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);S.uniform3iv(V(a),d)}},Ab:function(a,b,c){if(2<=Q.version)b&&S.uniform4fv(V(a),
y,c>>2,4*b);else{if(72>=b){var d=W[4*b-1],e=y;c>>=2;for(var h=0;h<4*b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);S.uniform4fv(V(a),d)}},wb:function(a,b,c){if(2<=Q.version)b&&S.uniform4iv(V(a),w,c>>2,4*b);else{if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);S.uniform4iv(V(a),d)}},vb:function(a,b,c,d){if(2<=Q.version)b&&S.uniformMatrix4fv(V(a),
!!c,y,d>>2,16*b);else{if(18>=b){var e=W[16*b-1],h=y;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=h[m];e[f+1]=h[m+1];e[f+2]=h[m+2];e[f+3]=h[m+3];e[f+4]=h[m+4];e[f+5]=h[m+5];e[f+6]=h[m+6];e[f+7]=h[m+7];e[f+8]=h[m+8];e[f+9]=h[m+9];e[f+10]=h[m+10];e[f+11]=h[m+11];e[f+12]=h[m+12];e[f+13]=h[m+13];e[f+14]=h[m+14];e[f+15]=h[m+15]}}else e=y.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(V(a),!!c,e)}},m:function(a){a=L[a];S.useProgram(a);S.Vc=a},Fb:function(a,b){S.vertexAttribDivisor(a,b)},Gb:function(a,b,c,
d,e,h){S.vertexAttribPointer(a,b,c,!!d,e,h)},q:function(a,b,c,d){S.viewport(a,b,c,d)},Ta:function(){g.Mc=a=>{0!=Wb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Mc)},Pa:function(){g.Sc=a=>{const b=a.clipboardData.getData("text");Na(()=>{const c=Y(b);Xb(c)})};window.addEventListener("paste",g.Sc)},Ia:function(a){g.kd=[];a=H(a);a=document.getElementById(a);g.Nc=b=>{b.stopPropagation();b.preventDefault()};g.Oc=b=>{b.stopPropagation();b.preventDefault()};g.Pc=b=>
{b.stopPropagation();b.preventDefault()};g.Qc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Rc=c;Yb(c.length);for(let d=0;d<c.length;d++)Na(()=>{const e=Y(c[d].name);Zb(d,e)});$b(b.clientX,b.clientY)};a.addEventListener("dragenter",g.Nc,!1);a.addEventListener("dragleave",g.Oc,!1);a.addEventListener("dragover",g.Pc,!1);a.addEventListener("drop",g.Qc,!1)},qb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},s:function(){const a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){ac()});document.body.append(a)},Ba:function(a){const b=g.Rc;return 0>a||a>=b.length?0:b[a].size},Rb:function(a,b,c,d,e){const h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?bc(a,0,1,b,0,c,d,e):(v.set(new Uint8Array(f),c),bc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{bc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.Rc[a])},p:function(){document.getElementById("_sokol_app_input_element").focus()},
Jb:function(a){a=H(a);g.wc=document.getElementById(a);g.wc||console.log("sokol_app.h: invalid target:"+a);g.wc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Sa:function(){window.removeEventListener("beforeunload",g.Mc)},La:function(){window.removeEventListener("paste",g.Sc)},Kb:function(a){a=H(a);a=document.getElementById(a);a.removeEventListener("dragenter",g.Nc);a.removeEventListener("dragleave",g.Oc);a.removeEventListener("dragover",g.Pc);a.removeEventListener("drop",
g.Qc)},z:function(){g.wc&&g.wc.requestPointerLock&&g.wc.requestPointerLock()},fb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(v.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},o:function(){document.getElementById("_sokol_app_input_element").blur()},_a:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];Na(()=>{const e=Y(c),h=Y(d);cc(e,h)})}},$a:function(){return g.tc?g.tc.bufferSize:0},bb:function(a,b,c){g.oc=null;g.tc=null;"undefined"!==typeof AudioContext?g.oc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.oc=null,console.log("sokol_audio.h: no WebAudio support"));return g.oc?(console.log("sokol_audio.h: sample rate ",g.oc.sampleRate),g.tc=g.oc.createScriptProcessor(c,0,b),g.tc.onaudioprocess=d=>{const e=d.outputBuffer.length,
h=dc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let m=0;m<f;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=y[(h>>2)+(f*p+m)]}}},g.tc.connect(g.oc.destination),a=()=>{g.oc&&"suspended"===g.oc.state&&g.oc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ab:function(){return g.oc?g.oc.sampleRate:0},ja:function(){const a=g.oc;null!==a&&(g.tc&&g.tc.disconnect(),
a.close(),g.oc=null,g.tc=null)},y:function(a,b,c,d,e,h){b=H(b);const f=new XMLHttpRequest;f.open("GET",b);f.responseType="arraybuffer";const m=0<d;m&&f.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));f.onreadystatechange=function(){if(f.readyState==XMLHttpRequest.DONE)if(206==f.status||200==f.status&&!m){const n=new Uint8Array(f.response),p=n.length;p<=h?(v.set(n,e),ec(a,d,p)):fc(a)}else gc(a,f.status)};f.send()},ia:function(a,b){b=H(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=
function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");hc(a,d)}else gc(a,c.status)};c.send()},ha:function(a,b){b=H(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;g.asm=c;oa=g.asm.Tb;ta();ua=g.asm.kc;wa.unshift(g.asm.Ub);A--;g.monitorRunDependencies&&g.monitorRunDependencies(A);if(0==A&&(null!==Ba&&(clearInterval(Ba),Ba=null),B)){var d=B;B=null;d()}return c}var b={a:ic};A++;g.monitorRunDependencies&&g.monitorRunDependencies(A);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return r("Module.instantiateWasm callback failed with error: "+c),!1}Ha(b,function(c){a(c.instance)});return{}})();
function E(){return(E=g.asm.Vb).apply(null,arguments)}g._fs_emsc_alloc=function(){return(g._fs_emsc_alloc=g.asm.Wb).apply(null,arguments)};g._fs_emsc_load_snapshot_callback=function(){return(g._fs_emsc_load_snapshot_callback=g.asm.Xb).apply(null,arguments)};
var ac=g.__sapp_emsc_notify_keyboard_hidden=function(){return(ac=g.__sapp_emsc_notify_keyboard_hidden=g.asm.Yb).apply(null,arguments)},Xb=g.__sapp_emsc_onpaste=function(){return(Xb=g.__sapp_emsc_onpaste=g.asm.Zb).apply(null,arguments)},Wb=g.__sapp_html5_get_ask_leave_site=function(){return(Wb=g.__sapp_html5_get_ask_leave_site=g.asm._b).apply(null,arguments)},Yb=g.__sapp_emsc_begin_drop=function(){return(Yb=g.__sapp_emsc_begin_drop=g.asm.$b).apply(null,arguments)},Zb=g.__sapp_emsc_drop=function(){return(Zb=
g.__sapp_emsc_drop=g.asm.ac).apply(null,arguments)},$b=g.__sapp_emsc_end_drop=function(){return($b=g.__sapp_emsc_end_drop=g.asm.bc).apply(null,arguments)},bc=g.__sapp_emsc_invoke_fetch_cb=function(){return(bc=g.__sapp_emsc_invoke_fetch_cb=g.asm.cc).apply(null,arguments)},jc=g._main=function(){return(jc=g._main=g.asm.dc).apply(null,arguments)},dc=g.__saudio_emsc_pull=function(){return(dc=g.__saudio_emsc_pull=g.asm.ec).apply(null,arguments)},cc=g.__sargs_add_kvp=function(){return(cc=g.__sargs_add_kvp=
g.asm.fc).apply(null,arguments)},hc=g.__sfetch_emsc_head_response=function(){return(hc=g.__sfetch_emsc_head_response=g.asm.gc).apply(null,arguments)},ec=g.__sfetch_emsc_get_response=function(){return(ec=g.__sfetch_emsc_get_response=g.asm.hc).apply(null,arguments)},gc=g.__sfetch_emsc_failed_http_status=function(){return(gc=g.__sfetch_emsc_failed_http_status=g.asm.ic).apply(null,arguments)},fc=g.__sfetch_emsc_failed_buffer_too_small=function(){return(fc=g.__sfetch_emsc_failed_buffer_too_small=g.asm.jc).apply(null,
arguments)};function Oa(){return(Oa=g.asm.lc).apply(null,arguments)}function Pa(){return(Pa=g.asm.mc).apply(null,arguments)}function Tb(){return(Tb=g.asm.nc).apply(null,arguments)}g.___start_em_js=26260;g.___stop_em_js=39154;var kc;B=function lc(){kc||mc();kc||(B=lc)};function nc(a=[]){var b=jc;a.unshift(ca);var c=a.length,d=Tb(4*(c+1)),e=d>>2;a.forEach(f=>{w[e++]=Y(f)});w[e]=0;try{var h=b(c,d);Nb(h,!0)}catch(f){f instanceof la||"unwind"==f||da(1,f)}}
function mc(){var a=ba;function b(){if(!kc&&(kc=!0,g.calledRun=!0,!pa)){Ia(wa);Ia(xa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();oc&&nc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.unshift(c)}Ia(za)}}if(!(0<A)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();Ia(va);0<A||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},
1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var oc=!0;g.noInitialRun&&(oc=!1);mc();
