var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(a){throw a;});k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;if(!(b instanceof w)){var c=b;b&&"object"==typeof b&&b.stack&&(c=[b,b.stack]);x("exiting due to exception: "+c)}process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),
q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var ia=f.print||console.log.bind(console),x=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&ja("no native wasm support detected");var ka,la=!1,ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?na(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var pa,A,qa,ra,C,D,E,F;function sa(){var a=ka.buffer;f.HEAP8=pa=new Int8Array(a);f.HEAP16=qa=new Int16Array(a);f.HEAP32=C=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=ra=new Uint16Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=E=new Float32Array(a);f.HEAPF64=F=new Float64Array(a)}var ta,ua=[],va=[],wa=[],xa=[],ya=[];
function za(){var a=f.preRun.shift();ua.unshift(a)}var G=0,Aa=null,H=null;function ja(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);la=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ba(a){return a.startsWith("data:application/octet-stream;base64,")}var I;I="raw.wasm";if(!Ba(I)){var Ca=I;I=f.locateFile?f.locateFile(Ca,q):q+Ca}
function Da(a){try{if(a==I&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){ja(b)}}
function Ea(a){if(!y&&(da||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return Da(a)});if(u)return new Promise(function(b,c){u(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return Da(a)})}
function Fa(a,b,c){return Ea(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){x("failed to asynchronously prepare wasm: "+d);ja(d)})}
function Ga(a,b){var c=I;y||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||c.startsWith("file://")||ea||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Fa(c,a,b)})})}function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Ha(a){for(;0<a.length;)a.shift()(f)}var Ia=[0,31,60,91,121,152,182,213,244,274,305,335],Ja=[0,31,59,90,120,151,181,212,243,273,304,334];function Ka(a){var b=oa(a)+1,c=J(b);c&&B(a,pa,c,b);return c}function La(a){var b=Ma();a();Na(b)}var Oa=0;function Pa(){for(var a=K.length-1;0<=a;--a)Qa(a);K=[];Ra=[]}var Ra=[];function Sa(){if(Oa&&Ta.nc)for(var a=0;a<Ra.length;++a){var b=Ra[a];Ra.splice(a,1);--a;b.Wc.apply(null,b.Nc)}}var K=[];
function Qa(a){var b=K[a];b.target.removeEventListener(b.ec,b.Ic,b.fc);K.splice(a,1)}function L(a){function b(d){++Oa;Ta=a;Sa();a.ic(d);Sa();--Oa}if(a.hc)a.Ic=b,a.target.addEventListener(a.ec,b,a.fc),K.push(a),Ua||(xa.push(Pa),Ua=!0);else for(var c=0;c<K.length;++c)K[c].target==a.target&&K[c].ec==a.ec&&Qa(c--)}function Va(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ua,Ta,Wa,Xa,Ya,Za,$a,ab,bb,cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function M(a){a=2<a?z(a):a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function db(a){return 0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var eb=[];function N(a){var b=eb[a];b||(a>=eb.length&&(eb.length=a+1),eb[a]=b=ta.get(a));return b}
function fb(a,b,c,d,e,h){Wa||(Wa=J(256));a={target:M(a),ec:h,hc:d,ic:function(g=event){var m=g.target.id?g.target.id:"",n=Wa;B(Va(g.target),A,n+0,128);B(m,A,n+128,128);N(d)(e,n,b)&&g.preventDefault()},fc:c};L(a)}
function gb(a,b,c,d,e,h){Xa||(Xa=J(176));a={target:M(a),nc:!0,ec:h,hc:d,ic:function(g){var m=Xa;F[m>>3]=g.timeStamp;var n=m>>2;C[n+2]=g.location;C[n+3]=g.ctrlKey;C[n+4]=g.shiftKey;C[n+5]=g.altKey;C[n+6]=g.metaKey;C[n+7]=g.repeat;C[n+8]=g.charCode;C[n+9]=g.keyCode;C[n+10]=g.which;B(g.key||"",A,m+44,32);B(g.code||"",A,m+76,32);B(g.char||"",A,m+108,32);B(g.locale||"",A,m+140,32);N(d)(e,m,b)&&g.preventDefault()},fc:c};L(a)}
function hb(a,b,c){F[a>>3]=b.timeStamp;a>>=2;C[a+2]=b.screenX;C[a+3]=b.screenY;C[a+4]=b.clientX;C[a+5]=b.clientY;C[a+6]=b.ctrlKey;C[a+7]=b.shiftKey;C[a+8]=b.altKey;C[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;C[a+11]=b.movementX;C[a+12]=b.movementY;c=db(c);C[a+13]=b.clientX-c.left;C[a+14]=b.clientY-c.top}
function O(a,b,c,d,e,h){Ya||(Ya=J(72));a=M(a);L({target:a,nc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ec:h,hc:d,ic:function(g=event){hb(Ya,g,a);N(d)(e,Ya,b)&&g.preventDefault()},fc:c})}function ib(a,b,c,d,e){Za||(Za=J(260));L({target:a,ec:e,hc:d,ic:function(h=event){var g=Za,m=document.pointerLockElement||document.kc||document.vc||document.tc;C[g>>2]=!!m;var n=m&&m.id?m.id:"";B(Va(m),A,g+4,128);B(n,A,g+132,128);N(d)(20,g,b)&&h.preventDefault()},fc:c})}
function jb(a,b,c,d,e){L({target:a,ec:e,hc:d,ic:function(h=event){N(d)(38,0,b)&&h.preventDefault()},fc:c})}function kb(a,b,c,d){$a||($a=J(36));a=M(a);L({target:a,ec:"resize",hc:d,ic:function(e=event){if(e.target==a){var h=document.body;if(h){var g=$a;C[g>>2]=e.detail;C[g+4>>2]=h.clientWidth;C[g+8>>2]=h.clientHeight;C[g+12>>2]=innerWidth;C[g+16>>2]=innerHeight;C[g+20>>2]=outerWidth;C[g+24>>2]=outerHeight;C[g+28>>2]=pageXOffset;C[g+32>>2]=pageYOffset;N(d)(10,g,b)&&e.preventDefault()}}},fc:c})}
function lb(a,b,c,d,e,h){ab||(ab=J(1696));a=M(a);L({target:a,nc:"touchstart"==h||"touchend"==h,ec:h,hc:d,ic:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.wc=m.xc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.wc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].xc=1;p=ab;F[p>>3]=g.timeStamp;var t=p>>2;C[t+3]=g.ctrlKey;C[t+4]=g.shiftKey;C[t+5]=g.altKey;C[t+6]=g.metaKey;t+=7;var nb=db(a),ob=0;for(r in n)if(m=
n[r],C[t]=m.identifier,C[t+1]=m.screenX,C[t+2]=m.screenY,C[t+3]=m.clientX,C[t+4]=m.clientY,C[t+5]=m.pageX,C[t+6]=m.pageY,C[t+7]=m.wc,C[t+8]=m.xc,C[t+9]=m.clientX-nb.left,C[t+10]=m.clientY-nb.top,t+=13,31<++ob)break;C[p+8>>2]=ob;N(d)(e,p,b)&&g.preventDefault()},fc:c})}function mb(a,b,c,d,e,h){a={target:M(a),ec:h,hc:d,ic:function(g=event){N(d)(e,0,b)&&g.preventDefault()},fc:c};L(a)}
function pb(a,b,c,d){bb||(bb=J(104));L({target:a,nc:!0,ec:"wheel",hc:d,ic:function(e=event){var h=bb;hb(h,e,a);F[h+72>>3]=e.deltaX;F[h+80>>3]=e.deltaY;F[h+88>>3]=e.deltaZ;C[h+96>>2]=e.deltaMode;N(d)(9,h,b)&&e.preventDefault()},fc:c})}
function qb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function rb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function sb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function tb(a){a.Sc=a.getExtension("WEBGL_multi_draw")}
var ub=1,vb=[],P=[],wb=[],Q=[],R=[],S=[],xb=[],yb={},zb=4;function T(a){Ab||(Ab=a)}function Bb(a){for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b}function Cb(a,b){a.kc||(a.kc=a.getContext,a.getContext=function(d,e){e=a.kc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Db(c,b):0}function Db(a,b){var c=Bb(xb),d={Qc:c,attributes:b,version:b.Lc,rc:a};a.canvas&&(a.canvas.Mc=d);xb[c]=d;("undefined"==typeof b.uc||b.uc)&&Eb(d);return c}
function Eb(a){a||(a=Fb);if(!a.Kc){a.Kc=!0;var b=a.rc;qb(b);rb(b);sb(b);b.Pc=b.getExtension("EXT_disjoint_timer_query");tb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ab,Fb,Gb=["default","low-power","high-performance"];function Hb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);la=!0}k(a,new w(a))}var Ib=[null,[],[]];
function Jb(a,b,c,d){for(var e=0;e<a;e++){var h=U[c](),g=h&&Bb(d);h?(h.name=g,d[g]=h):T(1282);C[b+4*e>>2]=g}}
function Kb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:T(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)C[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:T(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}C[b>>2]=c}else T(1281)}function Lb(a){var b=oa(a)+1,c=J(b);B(a,A,c,b);return c}
function Mb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Nb(a,b,c,d,e){a-=5120;a=1==a?A:4==a?C:6==a?E:5==a||28922==a?D:ra;var h=31-Math.clz32(a.BYTES_PER_ELEMENT),g=zb;return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+g-1&-g)>>h)}function V(a){var b=U.Hc;if(b){var c=b.mc[a];"number"==typeof c&&(b.mc[a]=c=U.getUniformLocation(b,b.Fc[a]+(0<c?"["+c+"]":"")));return c}T(1282)}var W=[],X=[];function Y(a){var b=oa(a)+1,c=Ob(b);B(a,pa,c,b);return c}
for(var U,Pb=new Float32Array(288),Z=0;288>Z;++Z)W[Z]=Pb.subarray(0,Z+1);var Qb=new Int32Array(288);for(Z=0;288>Z;++Z)X[Z]=Qb.subarray(0,Z+1);
var dc={fb:function(a){var b=new Date(C[a+20>>2]+1900,C[a+16>>2],C[a+12>>2],C[a+8>>2],C[a+4>>2],C[a>>2],0),c=C[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(h,e);0>c?C[a+32>>2]=Number(e!=h&&g==d):0<c!=(g==d)&&(e=Math.max(h,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));C[a+24>>2]=b.getDay();c=b.getFullYear();C[a+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ja:Ia)[b.getMonth()]+b.getDate()-1|0;C[a>>2]=
b.getSeconds();C[a+4>>2]=b.getMinutes();C[a+8>>2]=b.getHours();C[a+12>>2]=b.getDate();C[a+16>>2]=b.getMonth();C[a+20>>2]=b.getYear();return b.getTime()/1E3|0},gb:function(a,b,c){function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),h=new Date(e,0,1),g=new Date(e,6,1);e=h.getTimezoneOffset();var m=g.getTimezoneOffset();D[a>>2]=60*Math.max(e,m);C[b>>2]=Number(e!=m);a=d(h);b=d(g);a=Ka(a);b=Ka(b);m<e?(D[c>>2]=a,D[c+4>>2]=b):(D[c>>2]=b,D[c+4>>2]=
a)},k:function(){ja("")},eb:function(){return Date.now()},qa:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},H:function(a,b,c){a=M(a);if(!a)return-4;a=db(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},bb:function(a,b,c){A.copyWithin(a,b,b+c)},ub:function(a,b){function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ab:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=
Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var g=ka.buffer;try{ka.grow(h.call(e,2147483648,d)-g.byteLength+65535>>>16);sa();var m=1;break a}catch(n){}m=void 0}if(m)return!0}return!1},T:function(a,b,c,d){fb(a,b,c,d,12,"blur");return 0},na:function(a,b,c){a=M(a);if(!a)return-4;a.width=b;a.height=c;return 0},U:function(a,b,c,d){fb(a,b,c,d,13,"focus");return 0},ba:function(a,b,c,d){gb(a,b,c,d,2,"keydown");return 0},$:function(a,b,c,d){gb(a,b,c,d,1,"keypress");return 0},aa:function(a,b,c,
d){gb(a,b,c,d,3,"keyup");return 0},ha:function(a,b,c,d){O(a,b,c,d,5,"mousedown");return 0},ea:function(a,b,c,d){O(a,b,c,d,33,"mouseenter");return 0},da:function(a,b,c,d){O(a,b,c,d,34,"mouseleave");return 0},fa:function(a,b,c,d){O(a,b,c,d,8,"mousemove");return 0},ga:function(a,b,c,d){O(a,b,c,d,6,"mouseup");return 0},W:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.kc||document.body.vc||document.body.tc))return-1;a=M(a);if(!a)return-4;ib(a,b,c,d,"pointerlockchange");
ib(a,b,c,d,"mozpointerlockchange");ib(a,b,c,d,"webkitpointerlockchange");ib(a,b,c,d,"mspointerlockchange");return 0},V:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.kc||document.body.vc||document.body.tc))return-1;a=M(a);if(!a)return-4;jb(a,b,c,d,"pointerlockerror");jb(a,b,c,d,"mozpointerlockerror");jb(a,b,c,d,"webkitpointerlockerror");jb(a,b,c,d,"mspointerlockerror");return 0},xa:function(a,b,c,d){kb(a,b,c,d);return 0},X:function(a,b,c,d){lb(a,b,c,d,25,"touchcancel");
return 0},Y:function(a,b,c,d){lb(a,b,c,d,23,"touchend");return 0},Z:function(a,b,c,d){lb(a,b,c,d,24,"touchmove");return 0},_:function(a,b,c,d){lb(a,b,c,d,22,"touchstart");return 0},S:function(a,b,c,d){mb(a,b,c,d,31,"webglcontextlost");return 0},R:function(a,b,c,d){mb(a,b,c,d,32,"webglcontextrestored");return 0},ca:function(a,b,c,d){a=M(a);return"undefined"!=typeof a.onwheel?(pb(a,b,c,d),0):-1},ia:function(a,b){b>>=2;b={alpha:!!C[b],depth:!!C[b+1],stencil:!!C[b+2],antialias:!!C[b+3],premultipliedAlpha:!!C[b+
4],preserveDrawingBuffer:!!C[b+5],powerPreference:Gb[C[b+6]],failIfMajorPerformanceCaveat:!!C[b+7],Lc:C[b+8],Rc:C[b+9],uc:C[b+10],Jc:C[b+11],Tc:C[b+12],Uc:C[b+13]};a=M(a);return!a||b.Jc?0:Cb(a,b)},Za:function(a,b){a=xb[a];b=z(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&qb(U);"OES_vertex_array_object"==b&&rb(U);"WEBGL_draw_buffers"==b&&sb(U);"WEBGL_multi_draw"==b&&tb(U);return!!a.rc.getExtension(b)},jb:function(a){a>>=2;for(var b=0;14>b;++b)C[a+b]=0;C[a]=C[a+1]=C[a+3]=C[a+
4]=C[a+8]=C[a+10]=1},_a:function(a){Fb=xb[a];f.Oc=U=Fb&&Fb.rc;return!a||U?0:-5},Hb,cb:function(){return 52},$a:function(){return 70},db:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=D[b>>2],m=D[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=A[g+n],r=Ib[a];0===p||10===p?((1===a?ia:x)(na(r,0)),r.length=0):r.push(p)}e+=m}D[d>>2]=e;return 0},f:function(a){U.activeTexture(a)},G:function(a,b){U.attachShader(P[a],S[b])},b:function(a,b){U.bindBuffer(a,vb[b])},h:function(a,b){U.bindFramebuffer(a,wb[b])},Ea:function(a,
b){U.bindRenderbuffer(a,Q[b])},a:function(a,b){U.bindTexture(a,R[b])},L:function(a,b,c,d){U.blendColor(a,b,c,d)},M:function(a,b){U.blendEquationSeparate(a,b)},N:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},Ga:function(a,b,c,d){U.bufferData(a,c?A.subarray(c,c+b):b,d)},r:function(a,b,c,d){U.bufferSubData(a,b,A.subarray(d,d+c))},p:function(a){return U.checkFramebufferStatus(a)},Db:function(a){U.clear(a)},Fb:function(a,b,c,d){U.clearColor(a,b,c,d)},oa:function(a){U.clearDepth(a)},Eb:function(a){U.clearStencil(a)},
n:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},ta:function(a){U.compileShader(S[a])},Ba:function(a,b,c,d,e,h,g,m){U.compressedTexImage2D(a,b,c,d,e,h,m?A.subarray(m,m+g):null)},za:function(){var a=Bb(P),b=U.createProgram();b.name=a;b.qc=b.oc=b.pc=0;b.sc=1;P[a]=b;return a},va:function(a){var b=Bb(S);S[b]=U.createShader(a);return b},I:function(a){U.cullFace(a)},Na:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=vb[d];e&&(U.deleteBuffer(e),e.name=0,vb[d]=null)}},c:function(a,b){for(var c=0;c<
a;++c){var d=C[b+4*c>>2],e=wb[d];e&&(U.deleteFramebuffer(e),e.name=0,wb[d]=null)}},A:function(a){if(a){var b=P[a];b?(U.deleteProgram(b),b.name=0,P[a]=null):T(1281)}},P:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=Q[d];e&&(U.deleteRenderbuffer(e),e.name=0,Q[d]=null)}},w:function(a){if(a){var b=S[a];b?(U.deleteShader(b),S[a]=null):T(1281)}},Ma:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=R[d];e&&(U.deleteTexture(e),e.name=0,R[d]=null)}},z:function(a){U.depthFunc(a)},y:function(a){U.depthMask(!!a)},
d:function(a){U.disable(a)},O:function(a){U.disableVertexAttribArray(a)},mb:function(a,b,c){U.drawArrays(a,b,c)},nb:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},ob:function(a,b,c,d){U.drawElements(a,b,c,d)},pb:function(a,b,c,d,e){U.drawElementsInstanced(a,b,c,d,e)},i:function(a){U.enable(a)},Ab:function(a){U.enableVertexAttribArray(a)},l:function(a,b,c,d){U.framebufferRenderbuffer(a,b,c,Q[d])},g:function(a,b,c,d,e){U.framebufferTexture2D(a,b,c,R[d],e)},J:function(a){U.frontFace(a)},Ha:function(a,
b){Jb(a,b,"createBuffer",vb)},m:function(a,b){Jb(a,b,"createFramebuffer",wb)},Fa:function(a,b){Jb(a,b,"createRenderbuffer",Q)},Ca:function(a,b){Jb(a,b,"createTexture",R)},ra:function(a,b){return U.getAttribLocation(P[a],z(b))},e:function(a,b){Kb(a,b)},wa:function(a,b,c,d){a=U.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,A,d,b):0;c&&(C[c>>2]=b)},F:function(a,b,c){if(c)if(a>=ub)T(1281);else if(a=P[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C[c>>2]=a.length+
1;else if(35719==b){if(!a.qc)for(b=0;b<U.getProgramParameter(a,35718);++b)a.qc=Math.max(a.qc,U.getActiveUniform(a,b).name.length+1);C[c>>2]=a.qc}else if(35722==b){if(!a.oc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.oc=Math.max(a.oc,U.getActiveAttrib(a,b).name.length+1);C[c>>2]=a.oc}else if(35381==b){if(!a.pc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.pc=Math.max(a.pc,U.getActiveUniformBlockName(a,b).length+1);C[c>>2]=a.pc}else C[c>>2]=U.getProgramParameter(a,b);else T(1281)},sa:function(a,
b,c,d){a=U.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,A,d,b):0;c&&(C[c>>2]=b)},D:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),C[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(S[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=U.getShaderParameter(S[a],b):T(1281)},Oa:function(a){var b=yb[a];if(!b){switch(a){case 7939:b=U.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Lb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
U.getParameter(a))||T(1280);b=b&&Lb(b);break;case 7938:b=Lb("OpenGL ES 2.0 ("+U.getParameter(7938)+")");break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Lb(b);break;default:T(1280)}yb[a]=b}return b},q:function(a,b){b=z(b);if(a=P[a]){var c=a,d=c.mc,e=c.Gc,h;if(!d)for(c.mc=d={},c.Fc={},h=0;h<U.getProgramParameter(c,35718);++h){var g=U.getActiveUniform(c,h);var m=g.name;
g=g.size;var n=Mb(m);n=0<n?m.slice(0,n):m;var p=c.sc;c.sc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Fc[p++]=n}c=a.mc;d=0;e=b;h=Mb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Gc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else T(1281);return-1},ya:function(a){a=P[a];U.linkProgram(a);a.mc=0;a.Gc={}},La:function(a,b){3317==a&&(zb=b);U.pixelStorei(a,b)},K:function(a,b){U.polygonOffset(a,b)},Da:function(a,b,c,d){U.renderbufferStorage(a,b,c,d)},pa:function(a,b,c,
d){U.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?C[d+4*h>>2]:-1;e+=z(C[c+4*h>>2],0>g?void 0:g)}U.shaderSource(S[a],e)},Ka:function(a,b,c){U.stencilFunc(a,b,c)},ma:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},x:function(a){U.stencilMask(a)},Ja:function(a,b,c){U.stencilOp(a,b,c)},la:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,e,h,g,m,n){U.texImage2D(a,b,c,d,e,h,g,m,n?Nb(m,g,d,e,n):null)},j:function(a,b,c){U.texParameteri(a,b,c)},lb:function(a,
b,c,d,e,h,g,m,n){var p=null;n&&(p=Nb(m,g,e,h,n));U.texSubImage2D(a,b,c,d,e,h,g,m,p)},zb:function(a,b,c){if(288>=b)for(var d=W[b-1],e=0;e<b;++e)d[e]=E[c+4*e>>2];else d=E.subarray(c>>2,c+4*b>>2);U.uniform1fv(V(a),d)},E:function(a,b){U.uniform1i(V(a),b)},vb:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);U.uniform1iv(V(a),d)},yb:function(a,b,c){if(144>=b)for(var d=W[2*b-1],e=0;e<2*b;e+=2)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2];else d=E.subarray(c>>
2,c+8*b>>2);U.uniform2fv(V(a),d)},tb:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);U.uniform2iv(V(a),d)},xb:function(a,b,c){if(96>=b)for(var d=W[3*b-1],e=0;e<3*b;e+=3)d[e]=E[c+4*e>>2],d[e+1]=E[c+(4*e+4)>>2],d[e+2]=E[c+(4*e+8)>>2];else d=E.subarray(c>>2,c+12*b>>2);U.uniform3fv(V(a),d)},sb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2];else d=
C.subarray(c>>2,c+12*b>>2);U.uniform3iv(V(a),d)},wb:function(a,b,c){if(72>=b){var d=W[4*b-1],e=E;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=E.subarray(c>>2,c+16*b>>2);U.uniform4fv(V(a),d)},rb:function(a,b,c){if(72>=b)for(var d=X[4*b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);U.uniform4iv(V(a),d)},qb:function(a,b,c,d){if(18>=b){var e=W[16*b-1],h=E;
d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=E.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(V(a),!!c,e)},o:function(a){a=P[a];U.useProgram(a);U.Hc=a},Bb:function(a,b){U.vertexAttribDivisor(a,b)},Cb:function(a,b,c,d,e,h){U.vertexAttribPointer(a,b,c,!!d,e,h)},v:function(a,
b,c,d){U.viewport(a,b,c,d)},Wa:function(){f.yc=a=>{0!=Rb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.yc)},Va:function(){f.Ec=a=>{const b=a.clipboardData.getData("text");La(()=>{const c=Y(b);Sb(c)})};window.addEventListener("paste",f.Ec)},Ua:function(a){f.Vc=[];a=z(a);a=document.getElementById(a);f.zc=b=>{b.stopPropagation();b.preventDefault()};f.Ac=b=>{b.stopPropagation();b.preventDefault()};f.Bc=b=>{b.stopPropagation();b.preventDefault()};f.Cc=b=>{b.stopPropagation();
b.preventDefault();const c=b.dataTransfer.files;f.Dc=c;Tb(c.length);for(let d=0;d<c.length;d++)La(()=>{const e=Y(c[d].name);Ub(d,e)});Vb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.zc,!1);a.addEventListener("dragleave",f.Ac,!1);a.addEventListener("dragover",f.Bc,!1);a.addEventListener("drop",f.Cc,!1)},Qa:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},u:function(){const a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";
a.autocapitalize="none";a.addEventListener("focusout",function(){Wb()});document.body.append(a)},Gb:function(a){const b=f.Dc;return 0>a||a>=b.length?0:b[a].size},Ya:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?Xb(a,0,1,b,0,c,d,e):(A.set(new Uint8Array(g),c),Xb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=()=>{Xb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Dc[a])},t:function(){document.getElementById("_sokol_app_input_element").focus()},Ia:function(a){a=z(a);f.lc=
document.getElementById(a);f.lc||console.log("sokol_app.h: invalid target:"+a);f.lc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ta:function(){window.removeEventListener("beforeunload",f.yc)},Sa:function(){window.removeEventListener("paste",f.Ec)},Ra:function(a){a=z(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.zc);a.removeEventListener("dragleave",f.Ac);a.removeEventListener("dragover",f.Bc);a.removeEventListener("drop",f.Cc)},
C:function(){f.lc&&f.lc.requestPointerLock&&f.lc.requestPointerLock()},Pa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(A.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},s:function(){document.getElementById("_sokol_app_input_element").blur()},Xa:function(){const a=(new URLSearchParams(window.location.search)).entries();
for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];La(()=>{const e=Y(c),h=Y(d);Yb(e,h)})}},hb:function(){return f.jc?f.jc.bufferSize:0},kb:function(a,b,c){f.dc=null;f.jc=null;"undefined"!==typeof AudioContext?f.dc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.dc=null,console.log("sokol_audio.h: no WebAudio support"));return f.dc?(console.log("sokol_audio.h: sample rate ",f.dc.sampleRate),f.jc=f.dc.createScriptProcessor(c,0,b),f.jc.onaudioprocess=d=>{const e=d.outputBuffer.length,
h=Zb(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let m=0;m<g;m++){const n=d.outputBuffer.getChannelData(m);for(let p=0;p<e;p++)n[p]=E[(h>>2)+(g*p+m)]}}},f.jc.connect(f.dc.destination),a=()=>{f.dc&&"suspended"===f.dc.state&&f.dc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ib:function(){return f.dc?f.dc.sampleRate:0},ka:function(){const a=f.dc;null!==a&&(f.jc&&f.jc.disconnect(),
a.close(),f.dc=null,f.jc=null)},B:function(a,b,c,d,e,h){b=z(b);const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!m){const n=new Uint8Array(g.response),p=n.length;p<=h?(A.set(n,e),$b(a,d,p)):ac(a)}else bc(a,g.status)};g.send()},ja:function(a,b){b=z(b);const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=
function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");cc(a,d)}else bc(a,c.status)};c.send()},Q:function(a,b){b=z(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
(function(){function a(c){c=c.exports;f.asm=c;ka=f.asm.Ib;sa();ta=f.asm.$b;va.unshift(f.asm.Jb);G--;f.monitorRunDependencies&&f.monitorRunDependencies(G);if(0==G&&(null!==Aa&&(clearInterval(Aa),Aa=null),H)){var d=H;H=null;d()}return c}var b={a:dc};G++;f.monitorRunDependencies&&f.monitorRunDependencies(G);if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return x("Module.instantiateWasm callback failed with error: "+c),!1}Ga(b,function(c){a(c.instance)});return{}})();
function J(){return(J=f.asm.Kb).apply(null,arguments)}f._fs_emsc_alloc=function(){return(f._fs_emsc_alloc=f.asm.Lb).apply(null,arguments)};f._fs_emsc_load_snapshot_callback=function(){return(f._fs_emsc_load_snapshot_callback=f.asm.Mb).apply(null,arguments)};
var Wb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Wb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Nb).apply(null,arguments)},Sb=f.__sapp_emsc_onpaste=function(){return(Sb=f.__sapp_emsc_onpaste=f.asm.Ob).apply(null,arguments)},Rb=f.__sapp_html5_get_ask_leave_site=function(){return(Rb=f.__sapp_html5_get_ask_leave_site=f.asm.Pb).apply(null,arguments)},Tb=f.__sapp_emsc_begin_drop=function(){return(Tb=f.__sapp_emsc_begin_drop=f.asm.Qb).apply(null,arguments)},Ub=f.__sapp_emsc_drop=function(){return(Ub=
f.__sapp_emsc_drop=f.asm.Rb).apply(null,arguments)},Vb=f.__sapp_emsc_end_drop=function(){return(Vb=f.__sapp_emsc_end_drop=f.asm.Sb).apply(null,arguments)},Xb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Xb=f.__sapp_emsc_invoke_fetch_cb=f.asm.Tb).apply(null,arguments)},ec=f._main=function(){return(ec=f._main=f.asm.Ub).apply(null,arguments)},Zb=f.__saudio_emsc_pull=function(){return(Zb=f.__saudio_emsc_pull=f.asm.Vb).apply(null,arguments)},Yb=f.__sargs_add_kvp=function(){return(Yb=f.__sargs_add_kvp=
f.asm.Wb).apply(null,arguments)},cc=f.__sfetch_emsc_head_response=function(){return(cc=f.__sfetch_emsc_head_response=f.asm.Xb).apply(null,arguments)},$b=f.__sfetch_emsc_get_response=function(){return($b=f.__sfetch_emsc_get_response=f.asm.Yb).apply(null,arguments)},bc=f.__sfetch_emsc_failed_http_status=function(){return(bc=f.__sfetch_emsc_failed_http_status=f.asm.Zb).apply(null,arguments)},ac=f.__sfetch_emsc_failed_buffer_too_small=function(){return(ac=f.__sfetch_emsc_failed_buffer_too_small=f.asm._b).apply(null,
arguments)};function Ma(){return(Ma=f.asm.ac).apply(null,arguments)}function Na(){return(Na=f.asm.bc).apply(null,arguments)}function Ob(){return(Ob=f.asm.cc).apply(null,arguments)}f.___start_em_js=18644;f.___stop_em_js=31538;var fc;H=function gc(){fc||hc();fc||(H=gc)};function ic(a=[]){var b=ec;a.unshift(ca);var c=a.length,d=Ob(4*(c+1)),e=d>>2;a.forEach(g=>{C[e++]=Y(g)});C[e]=0;try{var h=b(c,d);Hb(h,!0)}catch(g){g instanceof w||"unwind"==g||k(1,g)}}
function hc(){var a=ba;function b(){if(!fc&&(fc=!0,f.calledRun=!0,!la)){Ha(va);Ha(wa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();jc&&ic(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ya.unshift(c)}Ha(ya)}}if(!(0<G)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)za();Ha(ua);0<G||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var jc=!0;f.noInitialRun&&(jc=!1);hc();
